### ISSUE TITLE
Hol érhető el

### ISSUE THREAD

**Issue by bartanorbi** [nav-gov-hu/Online-Cash-Register-Logfile#1]
Sziasztok,
könyvelőként a kérdésem az lenne, hogy a lekérdezés hol érhető el? Már kerestem a kobak rendszert, de nem találtam.. Mikor lesz ennek a fejlesztésnek a bevezetése, elméletileg a harmadik negyedévre lett beígérve valamelyik doksiban..
Nagyon köszi, jó lenne, ha normálisan működne...

**Comment by NTCA-tax** [comment]
A szolgáltatás jelenleg is fejlesztés alatt áll, az eredetileg tervezett Q3-as bevezetés a COVID veszélyhelyzet hatásaira való tekintettel vélhetően valamivel később valósul meg.

**Comment by gkerekes** [comment]
Lehet mar esetleg tudni, hogy mikor lesz elerheto?

**Comment by renced42** [comment]
Sziasztok!
Zárom az Issue-t, mivel ezzel kapcsolatosan megjelent a NAV közlemény, tesztelési lehetőség 2022.10.11-től lesz lehetőség.
