### ISSUE TITLE
Tesztadat generálás

### ISSUE THREAD

**Issue by harmatilaszlo** [nav-gov-hu/Online-Cash-Register-Logfile#10]
Sziasztok!  Működik a tesztadat generálás?  500-as hibakód folyamatosan.

**Comment by renced42** [comment]
Kedves @harmatilaszlo kérlek küld el a kérést ha tudod. Szinte biztos, hogy a kérés nem jó, én most leteszteltem és tökéletesen működik.

**Comment by harmatilaszlo** [comment]
<?xml version="1.0" encoding="utf-8"?>
<GenerateCashRegisterTestDataRequest xmlns="http://schemas.nav.gov.hu/OPF/1.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
  <common:header>
    <common:requestId>202210181135254172501</common:requestId>
    <common:timestamp>2022-10-18T09:35:25.000Z</common:timestamp>
    <common:requestVersion>1.0</common:requestVersion>
    <common:headerVersion>1.0</common:headerVersion>
  </common:header>
  <common:user>
    <common:login>2547fjGF7bxBSsu</common:login>
    <common:passwordHash cryptoType='SHA-512'>E0DD46899B14B62E549494B1C51965F2C744B1D6B7685581B2ECE7BFBAAB1ADC97D7AA4DA3CAB2B47B4622699C043426F268A97ADB09E96B15022D53D96112D0</common:passwordHash>
    <common:taxNumber>11111111</common:taxNumber>
    <common:requestSignature cryptoType='SHA3-512'>C4F5C51EC60EF669A435D99B617F838A6538FB89231BBF6DE26E297DB82ACEB325FAD4A163BC169B7AFEAFC8931F30AD87BB16C1F52AD4693EFD266EDBE6A790</common:requestSignature>
  </common:user>
  <software>
    <softwareId>HU111111111PRG2022</softwareId>
    <softwareName>string</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>string</softwareMainVersion>
    <softwareDevName>próba Kft.</softwareDevName>
    <softwareDevContact>proba@proba.hu</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>21252222-1-37</softwareDevTaxNumber>
  </software>
  <generateCashRegisterTestDataParameter>
    <APNumber>AP123456</APNumber>
  </generateCashRegisterTestDataParameter>
</GenerateCashRegisterTestDataRequest>

(login és taxnumber átírva)

**Comment by harmatilaszlo** [comment]
<?xml version="1.0" encoding="utf-8"?>
<GenerateCashRegisterTestDataRequest xmlns="http://schemas.nav.gov.hu/OPF/1.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
  <common:header>
    <common:requestId>202210181135254172501</common:requestId>
    <common:timestamp>2022-10-18T09:35:25.000Z</common:timestamp>
    <common:requestVersion>1.0</common:requestVersion>
    <common:headerVersion>1.0</common:headerVersion>
  </common:header>
  <common:user>
    <common:login>2547fjGF7bxBSsu</common:login>
    <common:passwordHash cryptoType='SHA-512'>E0DD46899B14B62E549494B1C51965F2C744B1D6B7685581B2ECE7BFBAAB1ADC97D7AA4DA3CAB2B47B4622699C043426F268A97ADB09E96B15022D53D96112D0</common:passwordHash>
    <common:taxNumber>11111111</common:taxNumber>
    <common:requestSignature cryptoType='SHA3-512'>C4F5C51EC60EF669A435D99B617F838A6538FB89231BBF6DE26E297DB82ACEB325FAD4A163BC169B7AFEAFC8931F30AD87BB16C1F52AD4693EFD266EDBE6A790</common:requestSignature>
  </common:user>
  <software>
    <softwareId>HU111111111PRG2022</softwareId>
    <softwareName>string</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>string</softwareMainVersion>
    <softwareDevName>próba Kft.</softwareDevName>
    <softwareDevContact>proba@proba.hu</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>21252222-1-37</softwareDevTaxNumber>
  </software>
  <generateCashRegisterTestDataParameter>
    <APNumber>AP123456</APNumber>
  </generateCashRegisterTestDataParameter>
</GenerateCashRegisterTestDataRequest>

A login és taxnumber átírva.

**Comment by harmatilaszlo** [comment]
<?xml version="1.0" encoding="utf-8"?>
<GenerateCashRegisterTestDataRequest xmlns="http://schemas.nav.gov.hu/OPF/1.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
  <common:header>
    <common:requestId>202210181135254172501</common:requestId>
    <common:timestamp>2022-10-18T09:35:25.000Z</common:timestamp>
    <common:requestVersion>1.0</common:requestVersion>
    <common:headerVersion>1.0</common:headerVersion>
  </common:header>
  <common:user>
    <common:login>2547fjGF7bxBSsu</common:login>
    <common:passwordHash cryptoType='SHA-512'>E0DD46899B14B62E549494B1C51965F2C744B1D6B7685581B2ECE7BFBAAB1ADC97D7AA4DA3CAB2B47B4622699C043426F268A97ADB09E96B15022D53D96112D0</common:passwordHash>
    <common:taxNumber>11111111</common:taxNumber>
    <common:requestSignature cryptoType='SHA3-512'>C4F5C51EC60EF669A435D99B617F838A6538FB89231BBF6DE26E297DB82ACEB325FAD4A163BC169B7AFEAFC8931F30AD87BB16C1F52AD4693EFD266EDBE6A790</common:requestSignature>
  </common:user>
  <software>
    <softwareId>HU111111111PRG2022</softwareId>
    <softwareName>string</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>string</softwareMainVersion>
    <softwareDevName>próba Kft.</softwareDevName>
    <softwareDevContact>proba@proba.hu</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>21252222-1-37</softwareDevTaxNumber>
  </software>
  <generateCashRegisterTestDataParameter>
    <APNumber>AP123456</APNumber>
  </generateCashRegisterTestDataParameter>
</GenerateCashRegisterTestDataRequest>

**Comment by harmatilaszlo** [comment]
************
<?xml version="1.0" encoding="utf-8"?>
<GenerateCashRegisterTestDataRequest xmlns="http://schemas.nav.gov.hu/OPF/1.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
  <common:header>
    <common:requestId>202210181135254172501</common:requestId>
    <common:timestamp>2022-10-18T09:35:25.000Z</common:timestamp>
    <common:requestVersion>1.0</common:requestVersion>
    <common:headerVersion>1.0</common:headerVersion>
  </common:header>
  <common:user>
    <common:login>2547fjGF7bxBSsu</common:login>
    <common:passwordHash cryptoType='SHA-512'>E0DD46899B14B62E549494B1C51965F2C744B1D6B7685581B2ECE7BFBAAB1ADC97D7AA4DA3CAB2B47B4622699C043426F268A97ADB09E96B15022D53D96112D0</common:passwordHash>
    <common:taxNumber>11111111</common:taxNumber>
    <common:requestSignature cryptoType='SHA3-512'>C4F5C51EC60EF669A435D99B617F838A6538FB89231BBF6DE26E297DB82ACEB325FAD4A163BC169B7AFEAFC8931F30AD87BB16C1F52AD4693EFD266EDBE6A790</common:requestSignature>
  </common:user>
  <software>
    <softwareId>HU111111111PRG2022</softwareId>
    <softwareName>string</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>string</softwareMainVersion>
    <softwareDevName>próba Kft.</softwareDevName>
    <softwareDevContact>proba@proba.hu</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>21252222-1-37</softwareDevTaxNumber>
  </software>
  <generateCashRegisterTestDataParameter>
    <APNumber>AP123456</APNumber>
  </generateCashRegisterTestDataParameter>
</GenerateCashRegisterTestDataRequest>
******************

**Comment by harmatilaszlo** [comment]
<?xml version="1.0" encoding="utf-8"?>
<GenerateCashRegisterTestDataRequest xmlns="http://schemas.nav.gov.hu/OPF/1.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
  <common:header>
    <common:requestId>202210181135254172501</common:requestId>
    <common:timestamp>2022-10-18T09:35:25.000Z</common:timestamp>
    <common:requestVersion>1.0</common:requestVersion>
    <common:headerVersion>1.0</common:headerVersion>
  </common:header>
  <common:user>
    <common:login>2547fjGF7bxBSsu</common:login>
    <common:passwordHash cryptoType='SHA-512'>E0DD46899B14B62E549494B1C51965F2C744B1D6B7685581B2ECE7BFBAAB1ADC97D7AA4DA3CAB2B47B4622699C043426F268A97ADB09E96B15022D53D96112D0</common:passwordHash>
    <common:taxNumber>11111111</common:taxNumber>
    <common:requestSignature cryptoType='SHA3-512'>C4F5C51EC60EF669A435D99B617F838A6538FB89231BBF6DE26E297DB82ACEB325FAD4A163BC169B7AFEAFC8931F30AD87BB16C1F52AD4693EFD266EDBE6A790</common:requestSignature>
  </common:user>
  <software>
    <softwareId>HU111111111PRG2022</softwareId>
    <softwareName>string</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>string</softwareMainVersion>
    <softwareDevName>próba Kft.</softwareDevName>
    <softwareDevContact>proba@proba.hu</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>21252222-1-37</softwareDevTaxNumber>
  </software>
  <generateCashRegisterTestDataParameter>
    <APNumber>AP123456</APNumber>
  </generateCashRegisterTestDataParameter>
</GenerateCashRegisterTestDataRequest>

**Comment by harmatilaszlo** [comment]
[generate.pdf](https://github.com/nav-gov-hu/Online-Cash-Register-Logfile/files/9809109/generate.pdf)

**Comment by harmatilaszlo** [comment]
[generateCashRegisterTestDataRequest.zip](https://github.com/nav-gov-hu/Online-Cash-Register-Logfile/files/9809693/generateCashRegisterTestDataRequest.zip)

**Comment by laladisc** [comment]
Szia! Nálam is Http 500 hibakód jött az elején. A Http request content type-ot próbáld meg üresen hagyni. Én ezt az egy beállítást változtattam meg az Online számla küldéshez képest. Nekem ezek után már működött a teszt adat generálás.

**Comment by blaky** [comment]
Eleinte `application/xml` content-type-al hivtam en is meg, de arra hibat dobott, `application/soap+xml;charset=UTF-8`-al mukodik.
