### ISSUE TITLE
INVALID_SECURITY_USER[Q&A]

### ISSUE THREAD

**Issue by hepplaszlo** [nav-gov-hu/Online-Cash-Register-Logfile#11]
Üdvözlöm!
INVALID_SECURITY_USER hibaüzenetet kapunk. Létrehozott az online számla test rendszerben a pénztárgépet használó egy új technikai felhasználót, hozzárendelte, hogy lehessen ptg-t lekérdezni, generált kulcsokat is. Kérem segítsen mi lehet a hiba.

**Comment by renced42** [comment]
Kedves @hepplaszlo , ha nincs több kérdés zárom az issue-t.
