### ISSUE TITLE
[Q&A] <VAT> ÁFA-tábla, gyűjtők 

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Cash-Register-Logfile#13]
A rendelet leírja, hogy az egyes gyűjtőkhöz (A-E) milyen ÁFA-kulcsok tartoznak. Mivel nem tudom, hogyan működik a pénztárgép programozása, ezért nem tudom, ez mennyire megbízható a valóságban. Lehetséges, hogy a pénztárgép beállításakor teljesen másképpen osztják ezeket ki? Egyelőre csak tesztadatokon lehet próbálkozni, ahol a letölthető tesztadatok között is van ilyen ugyanazon pénztárgépnél a `<VAT>` értékeként:

`VATUPD~A00000002~20200720142046~A-10-10-10.00%~B-20-20-20.00%~C-30-30-30.00%~D-0-0-AJT~E-0-0-AM~000035775a`
`VATUPD~A00000002~20200721093058~A-5-4,76-04.76%~B-18-15,25-15.25%~C-27-21,26-21.26%~D-0-0-AJT~E-0-0-AM~000035dd72`

Annyiban kapcsolódik ide, hogy a `<VAT>` tagben ez lekérdezhető, viszont az adatok kibányászásához jó lenne tudni, hogy a tesztadatokban alkalmazott '~' elválasztó kötelezően az, vagy pénztárgépenként változhat. A rendeletben ugyanis a `VATUPD` üzenet formátumleírása nem tartalmazza ezt az elválasztó karaktert. Persze, ha száz százalékig biztos, hogy minden egyes pénztárgépben az egyes gyűjtők ugyanazt az ÁFA-kulcsot jelentik, akkor ez lényegtelen.

**Comment by renced42** [comment]
Kedves @pigator
Tartalmazza a 48/2013. (XI. 15.) NGM rendelet 5. melléklet  Az Adóügyi Ellenőrző Egység (AEE) és a NAV szerverei közötti kommunikáció protokolljára vonatkozó előírások13. pontja.
A jogtárak a "~" jelet előszeretettel "-"-re cserélik így a magyarkozlöny.hu-ról  a vonatkozó dátummal letöltött PDF-be benne van. (82194 oldal)
A VATUPD parancsot a NAV küldi ki, tehát az biztosan fix és minden pénztárgépben ugyanúgy van. Egészen addig amíg esetlegesen nem kerül ki vagy bevezetésre más áfakulcs.

**Comment by pigator** [comment]
Köszönöm. Azért voltam bizonytalan, mert a gyakorlatban már találkoztam olyannal, hogy 27%-os ÁFA-ra használtak A27 kódú gyűjtőt, illetve A00-t adómentes (0%)-ra. Ezek szerint ez teljes félreértelmezés a pénztárgép beüzemelője és használója részéről.

**Comment by renced42** [comment]
> Köszönöm. Azért voltam bizonytalan, mert a gyakorlatban már találkoztam olyannal, hogy 27%-os ÁFA-ra használtak A27 kódú gyűjtőt, illetve A00-t adómentes (0%)-ra. Ezek szerint ez teljes félreértelmezés a pénztárgép beüzemelője és használója részéről. 

Erről nem tudok nyilatkozni :), mindenesetre zárom az issue-t.

**Comment by sinick2** [comment]
Kedves @pigator 

Azt esetleg meg tudod mondani, hogy "A27" esetén a napi forgalmi összesítőn ("NFN") a "ZQQ" mezőkben megadott nyomtatáson ilyenkor 27%-os áfagyűjtőnek is "A"-t használ? (Azaz "A - 21,26%".)

Köszi, sinick

**Comment by sinick2** [comment]
OK, köszönöm!
