### ISSUE TITLE
P7B fájl leírás hol érhető el?

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Cash-Register-Logfile#15]
A P7B nem csak xml adatot tartalmaz hanem előtte és után van bináris adat is. Hol érhető el a fájl leírását tartalmazó dokumentáció?

Köszönöm.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
A p7b formátumról itt találsz leírást [https://www.rfc-editor.org/rfc/rfc2315](url)
Alapvetően ez egy PKI aláírás. Ezt az aláírást a AEE teszi rá az adatszolgáltatás tartalmazó XML-re.

**Comment by rgform** [comment]
T renced42!

Az Onlineszámla indulása óta igyekszem a NAV doksi alapján létrehozni működő programokat. Most előszőr ez a P7B formátumos adatlekérés kifogott rajtam.  A P7B formátumot emberemlékezet óta használjuk certificate-k kezelésére, de ilyennel amibe be van ágyazva az XML (előtte, utána bináris tartalommal) nem találkoztunk, és közel egy napos WEB-es keresés után sem találtunk semmi infót. A "parse xml from p7b", "read xml from p7b" stb keresések mindig kulcs exportáláshoz vezettek csak...  Kérhetnék BÁRMILYEN programnyelven egy mintát?!  Vagy ne P7B fájlként tekintsek rá, de akkor mi a "valódi" content-type szerinti fájlformátum?

Köszönöm.

**Comment by renced42** [comment]
Kedves @rgform  rendben teszek fel valami példakódot :)

**Comment by blaky** [comment]
Itt van egy (nem tul szep) megoldas node-ban:
```
import { EncapsulatedContentInfo } from 'pkijs';

const contentInfo = EncapsulatedContentInfo.fromBER(unzipResult.data);
const mainValueBlock: any = contentInfo.eContent?.valueBlock.value[2].valueBlock;
const xmlContent = Buffer.from(mainValueBlock.value[1].valueBlock.value[0].getValue()).toString('utf-8');
```

**Comment by renced42** [comment]
Kedves @rgform 

Csatolok egy mintát amin el lehet indulni Java úton.

A P7B állományból az alábbi kódrészlettel nyerhető ki hivatalosan a tartalom:

// A P7B állományból az XML kinyeréséhez ajánlott osztályok
import org.bouncycastle.cms.CMSException;
import org.bouncycastle.cms.CMSSignedData;
...
byte[] p7bFile; // A P7B állomány tartalma - input
byte[] xmlContent; // A P7B állományban lévő XML – output
…
// A P7B állományból az XML kinyerése
try {
                CMSSignedData signedData = new CMSSignedData(p7bFile);
                xmlContent = (byte[]) signedData.getSignedContent().getContent();
} 
// Hiba esetén kivétel dobás
catch (CMSException e) {
...
}

Ha esetleg még sem sikerül, bármilyen probléma miatt a kinyerés, akkor marad a minta alapú kitúrás.

// A P7B állományból az XML kinyeréséhez ajánlott osztályok
import org.bouncycastle.cms.CMSException;
import org.bouncycastle.cms.CMSSignedData;
                …
byte[] p7bFile; // A P7B állomány tartalma - input
byte[] xmlContent; // A P7B állományban lévő XML – output
String beginPattern = "<?xml"; // Az XML állomány kezdetének a mintája
String endPattern = "</ROWS>"; // Az XML állomány végének a mintája
…
                // A P7B állományból az XML kinyerése
                try {
                                CMSSignedData signedData = new CMSSignedData(p7bFile);
                                xmlContent = (byte[]) signedData.getSignedContent().getContent();
                } 
                // Ha nem sikerült a kinyerés a P7B állományból
                catch (CMSException e) {
                                try {
                                // Az XML tartalom megkeresése substring használatával
                               String tmpFile = new String(p7bFile);
                                xmlContent = tmpFile.substring(tmpFile.indexOf(beginPattern),
                                                               tmpFile.lastIndexOf(endPattern) + endPattern.length()).getBytes();
                               } catch (Exception e) {

**Comment by EPluribusUnum** [comment]
@renced42 , köszi, ezzel ment az xml kiolvasás.

**Comment by EPluribusUnum** [comment]
@rgform , crypto lib-ek esetén a legrosszab a saját kód használata.
SHA3-512-t is leporgramoztad? Java8-hoz pl. amiatt is kell a Bouncycastle.

**Comment by renced42** [comment]
> Köszönöm. Sajnos genetikailag írtózom a 3rd party dolgok használatától ért eddig kerültem a Bouncyt... Viszont így látom, hogy "sima" bytesorozat, akkor ott manipulálunk tovább.

Ahogy jónak látod :) zárom az Issuet.
