### ISSUE TITLE
[Q&A] Napi forgalmi jelentés - sztornó NSS vs. STS

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Cash-Register-Logfile#16]
A "Napi forgalmi jelentés" (`NFN`) -ben szereplő
`NSS` - a napi sztornó összesen, bruttó összegben, egész forintban számolva (20 karakteres numerikus)
és
`STS` - napi sztornó bizonylatok összértéke összesen, egész forintban, pozitív számként (10 karakteres numerikus)
között mi a különbség? A rendelet erre nem tér ki, ugyanakkor a tesztadatokban ugyanazon napi zárásban a kettő bejegyzés különböző értéket tartalmaz. Mi ennek az oka?

**Comment by renced42** [comment]
Kedves @pigator, továbbítottam a kérdést egy szakavatott kollégának, ha van válasz forwardolom.

**Comment by renced42** [comment]
Kedves @pigator 
Íme a válasz:

NSS 
A napi sztornó összesen, bruttó összegben, egész forintban számolva 
Azonos az adott napon kiadott összes NYN és ESN bizonylat olyan tételsoraiban szereplő SU elem értékeinek összegével, ahol a tételsor TY elemének értéke "s", ha CNC=0. Nemnegatív számként kell szerepeltetni.

STS 
Napi sztornó bizonylatok összértéke összesen, egész forintban, pozitív számként
Azonos az adott napon kiadott olyan sztornó bizonylatok SUM elemeinek összegével, ahol CNC=0. Nemnegatív számként kell szerepeltetni.

A sztornónak a pénztárgépes fogalomrendszerben „kettős” jelentése van. Egyrészt egy bizonylat típust jelent, a pénztárgéppel ugyanis kiállítható sztornó bizonylat (SZN). Másrészt egy tranzakció típust (tétel törlést) is jelent, ami nem csak sztornó bizonylaton, hanem nyugta (NYN) vagy egyszerűsített számla (ESN) esetén is alkalmazható (pl. felvisznek egy nyugtára 5 db-ot „A” tételből, majd nyugtán belül törölnek „A” tételből 2 db-ot, akkor ez utóbbi egy tétel sztornó tranzakció lesz nyugtán belül).
Az NSS mező a tétel sztornó tranzakciókat összesíti, vagyis a kiállított nyugta vagy egyszerűsített számla sztornózott tételeinek értékét (SU).

Az STS mező pedig a kiállított  sztornó bizonylatok összértékét (SUM) összesíti.

**Comment by pigator** [comment]
Köszönöm.
