### ISSUE TITLE
Karakterkódolási hiba

### ISSUE THREAD

**Issue by sinick2** [nav-gov-hu/Online-Cash-Register-Logfile#17]
Tisztelt Fejlesztők!

Az általam generált tesztadatokban a magyar ékezetes karakterek helyén egy kérdőjel jelenik meg. Elsőre a PJN és NFN-ben ZQQ illetve ESN-ben VED/NAM mezőkre lettem figyelmes, de gondolom az összes karakteres az.

Hibás a kódolás vagy én nézem rossz nézegetővel?

Ld. pl.: A12346578_[adószámom]_20200720134606_6.P7B

```
<ZQQ>----------------------------------------</ZQQ>
<ZQQ>?SSZESEN:                     2 349 Ft</ZQQ>
<ZQQ>----------------------------------------</ZQQ>
<ZQQ/>
<ZQQ>K?SZP?NZ:                     2 350 Ft</ZQQ>
<ZQQ>KEREK?T?S:                        1 Ft</ZQQ>
<ZQQ>----------------------------------------</ZQQ>
<ZQQ>A n?peg?szs?g?gyi term?kad?</ZQQ>
<ZQQ>a k?lf?ldr?l beszerzett term?kekre</ZQQ>
<ZQQ>a Tesco-Global Zrt-t terheli.</ZQQ>
<ZQQ/>
<ZQQ>KEZEL?: 3399  KASSZA:141  TR.SZ?M: 0001</ZQQ>
<ZQQ/>
<ZQQ>         K?SZ?NJ?K V?S?RL?S?T!</ZQQ>
<ZQQ/>
<ZQQ>***************************************</ZQQ>
<ZQQ>         NAV Ellen?rz? k?d:E6A0F</ZQQ>

```
```
<VED>
	<NAM>Kiss J?zsef ?s tsa Bt </NAM>
	<IRS>1047 </IRS>
	<TEL>Budapest</TEL>
	<KZT>Nagy</KZT>
	<KZJ>t?r</KZJ>
	<HSZ>12</HSZ>
	<ASZ>12345678-1-12</ASZ>
</VED>
```

**Comment by renced42** [comment]
Kedves @sinick2, köszi a jelzést megnézzük, lehet nálunk van a gikszer.

**Comment by sinick2** [comment]
Rendben, én is köszönöm!

Azt még meg szeretném kérdezni, hogy mennyire jellemző, hogy a pénztárgépek hibás kódolással küldenek be szöveges adatokat?

(Sikerült beszereznem néhány pénztárgép teszt naplófájlt és azokban azt látom, hogy vagy jók a magyar ékezetek vagy nem és szintén kérdőjelesek.)

**Comment by renced42** [comment]
Sziasztok!

Megnéztük, nálunk van a hiba, javítjuk hamarosan.

**Comment by githubuser01x** [comment]
Ha már legeneráltattam hibásan akkor a javítás után elég újrageneráltatnom és már jó lesz vagy szükséges törölni a régi teszt adatokat? Ha utóbbi akkor azt hogyan lehet megtenni?

**Comment by renced42** [comment]
> 

Kedves @githubuser01x, igen elég újragenerálni.

**Comment by wknav** [comment]
A hiba javításra került, a mai naptól a generált állományok már UTF8 karakterkódolásúak.
