### ISSUE TITLE
[Q&A] Naplóállomány lezárva (LCL) napi forgalmi jelentés (NFN) nélkül

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Cash-Register-Logfile#18]
A tesztadatok között (valószínű mindenkinek ugyanaz van) van olyan naplófájl, ami nem tartalmaz `NFN`-t, de le van zárva maga a naplófájl (`<EVC>LCL</EVC>`)
A naplófájl, amiről szó van:
`*_20200721072819_22.P7B` (* = saját AP szám + adószám)
az utolsó `EVT` hash (`HSH`):
`F286E414934332508045C800AB9C65420C466432C461D95C4C79009A3EFA5414`
Séma szerint ez szabályos, de érdekelne, hogy a valóságban ez mikor fordulhat elő. A naplófájl tartalmaz érdemleges adatot, `NYN`-t és `ESN`-t is. Ezek valamelyik következő naplófájl napi forgalmi jelentésében (`NFN`) lesznek?

**Comment by renced42** [comment]
> A tesztadatok között (valószínű mindenkinek ugyanaz van) van olyan naplófájl, ami nem tartalmaz `NFN`-t, de le van zárva maga a naplófájl (`<EVC>LCL</EVC>`) A naplófájl, amiről szó van: `*_20200721072819_22.P7B` (* = saját AP szám + adószám) az utolsó `EVT` hash (`HSH`): `F286E414934332508045C800AB9C65420C466432C461D95C4C79009A3EFA5414` Séma szerint ez szabályos, de érdekelne, hogy a valóságban ez mikor fordulhat elő. A naplófájl tartalmaz érdemleges adatot, `NYN`-t és `ESN`-t is. Ezek valamelyik következő naplófájl napi forgalmi jelentésében (`NFN`) lesznek?

Kedves @pigator 
A naplófájl valamilyen treshold vagy esemény hatására záródik le. Például:
- Napi záráskor
- Ha a NAV azonnali adatot kér
- Eléri a naplóállomány a NAV által beállított file méretet.
- Átszemélyesítés

49. § (1) A pénztárgépen a napi nyitás és napi zárás végrehajtása kötelező.
(2) A napi nyitás végrehajtása során rögzíteni kell a nyitó készpénzállomány értékét.
**(3) A pénztárgépen minden nyitvatartási nap végén, folyamatos nyitva tartás mellett 24 óránként „Napi forgalmi
jelentést”-t kell készíteni.**

**Comment by pigator** [comment]
Köszönöm.
Mi történik ebben az esetben azokkal a rögzített bizonylatokkal (`ESN`, `NYN`, stb.), amik a lezárt fájlban vannak, de ott nem kerültek napi  forgalmi jelentésbe? A következő fájl forgalmi jelentése (`NFN`) fogja ezeket tartalmazni? Azért kérdezem ezeket, mert nyilván a lekérdezés célja valamiféle összesítés kinyerése a pénztárgép adatokból, és a tesztadatok alapján egyáltalán nem biztos, hogy minden esetben található napi forgalmi jelentés (`NFN`) egy bizonylatokat tartalmazó lezárt fájlban, ami az összesítés alapjául szolgálhatna.

**Comment by renced42** [comment]
> Köszönöm. Mi történik ebben az esetben azokkal a rögzített bizonylatokkal (`ESN`, `NYN`, stb.), amik a lezárt fájlban vannak, de ott nem kerültek napi forgalmi jelentésbe? A következő fájl forgalmi jelentése (`NFN`) fogja ezeket tartalmazni? Azért kérdezem ezeket, mert nyilván a lekérdezés célja valamiféle összesítés kinyerése a pénztárgép adatokból, és a tesztadatok alapján egyáltalán nem biztos, hogy minden esetben található napi forgalmi jelentés (`NFN`) egy bizonylatokat tartalmazó lezárt fájlban, ami az összesítés alapjául szolgálhatna.

Nem napi egy állomány van. A napi forgalmi jelentést a pénztárgép a saját lelki világából álliítja ki. Azt a naplóállományoktól függetlenül tartja nyilván és számolja. Vagyis neked minden egyes naplóállományt végig kell nyálazni és amelyikben benne van abból kell kivenni.

**Comment by renced42** [comment]
Igen tartalmazza.

**Comment by pigator** [comment]
Köszönöm.
