### ISSUE TITLE
xsd sértés a generateCashRegisterTestData()-n keresztül létrehozott xml-ekben

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Cash-Register-Logfile#19]
https://github.com/nav-gov-hu/Online-Cash-Register-Logfile/blob/master/src/schemas/nav/gov/hu/OPG/V2_AEEnaplo_6.6.5.xsd

Az xsd-t megsértik a következő xml-ek

"cvc-datatype-valid.1.2.1: A(z) '0,00' nem értényes 'integer' érték." az 58-as fileNumber-nél
"cvc-datatype-valid.1.2.1: A(z) '41,92' nem értényes 'integer' érték." a 60-as fileNumber-nél
"cvc-datatype-valid.1.2.1: A(z) '0,00' nem értényes 'integer' érték." a 62-es fileNumber-nél
"cvc-datatype-valid.1.2.1: A(z) '333,50' nem értényes 'integer' érték. " a 64-es fileNumber-nél
"cvc-datatype-valid.1.2.1: A(z) '0,00' nem értényes 'integer' érték." a 65-ös fileNumber-nél

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
Az XSD hiba azért jelentkezett, mert a teszt állományokban legenerálásra kerültek olyan állományok is, amelyek már EURO üzemmódban történő működést is szimuláltak. Ezek az állományok a továbbiakban már nem kerülnek generálásra.
