### ISSUE TITLE
Mikorra várható az első teszt [Q&A]

### ISSUE THREAD

**Issue by vbela75** [nav-gov-hu/Online-Cash-Register-Logfile#2]
A kérdés, amire választ szeretnék kapni / The question I would like to be answered
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Érdeklődni szeretnék mikorra várható az első tesztelési lehetőség. Tervezném az idei fejlesztéseimet mikorra ütemezzem.

**Comment by renced42** [comment]
Kedves @vbela75 

A tesztelés várhatóan Q2 második felében lesz megnyitva.

**Comment by vbela75** [comment]
Kedves @renced42 !

Q2 második fele van. Szeretném kérdezni, hogy lesz belőle valami ebben a hónapban.

**Comment by vasadibt** [comment]
Tisztelettel, én is érdeklődnek, hogy mikorra várható.

**Comment by renced42** [comment]
Sziasztok!

Elnézést, hogy csak most válaszolok, sajnos ezzel a projektel meg vagyunk kicsit csúszva, de dolgozunk rajta.
Kis türelmet kérünk még.

Köszönöm!

**Comment by renced42** [comment]
Kedves @vbela75x 
Elnézést a késői válaszért.

A fejlesztés elkészült időközben, de van egy kis irányváltás a felhasználó kezelésben.
Ez azt jelenti, hogy az eredeti tervek szerint nem az OPG-s KOBAK rendszerbe valósul meg, hanem beintegráljuk az Online Számla rendszerbe.
Ez azt jelenti, hogy az ott meglévő vagy újként létrehozott technikai felhasználókkal lehet, majd az adatokat elkérni, újonan kialakított jogosultság bepipálásával.
Ezen kívül vannak még olyan biztonsági és auditálási adminisztrációk amiken túl kell, hogy essünk, mielőtt megnyitjuk a szolgáltatást. 
A jó hír, hogy lesz ennek a funkciónak is EDU környezete, ahol majd mindenki generáltathat saját teszt adatot gépi interfészen keresztül amit le is tölthet.
Illetve egy változás van most még folyamatban, hogy a jelenleg publikált XSD módosulni fog úgy, hogy a common.xsd-t importálni fogja, hiszen 2019-ben még ez nem volt meg. A jelenlegi specihez képest ez annyiban változik, hogy a password és a requestsignature elemekbe bejön a cryptoType attribútum illetve megjelennek a namespace elemek is az xml tagekben. Az új verziót hamarosan publikálni fogjuk.
Már célegyenesben vagyunk, így mindent kommunikálni fogunk, hogy lehessen rá készülni, viszont vannak mozgó pontok a NAV-on kívül, ami miatt a NAV még nem tud pontos időpontot mondani jelenleg, de ez is hamarosan kiderül.

Az új infókkal nemsokára jelentkezni fogunk.

**Comment by vbela75x** [comment]
Kedves @renced42 

Köszönjük a részletes választ. Alig várjuk már a lehetőséget. :)

**Comment by rrd108** [comment]
van már erre kitűzött határidő?

**Comment by trekobt** [comment]
Kíváncsian várjuk az újabb híreket a folytatásról :)
Történt-e ebben a témában érdemleges előrelépés az utolsó releváns hír óta?

**Comment by renced42** [comment]
Kedves @trekobt, tudomásom szerint hamarosan meg fog jelenni egy tájékoztató a NAV honlapján a szolgáltatással kapcsolatosan.

**Comment by tothj74** [comment]
Kedves @renced42 , ez jó hír, alig várjuk. :-)

**Comment by blaky** [comment]
Esetleg van valami újabb információ?

**Comment by renced42** [comment]
Sziasztok!
Zárom az Issue-t, mivel ezzel kapcsolatosan megjelent a NAV közlemény, tesztelési lehetőség 2022.10.11-től lesz lehetőség.
