### ISSUE TITLE
Napi lekérdezés 

### ISSUE THREAD

**Issue by pelach** [nav-gov-hu/Online-Cash-Register-Logfile#20]
Üdv!
Lesz-e lehetőség egy megadott dátum intervallum alapján történő lekérdezésre?
Számlázó programom van és csak a napi pénztárgépes értékesítés ellenőrzésére lenne használva.
Viszont a mostani formában erre nem igazán alkalmas.

Köszönöm

**Comment by renced42** [comment]
Kedves @pelach Az interfész arra készül, hogy az adózó oldalán minden lekérdezhető naplófájl lekérdezésre kerül sorban.  A naplóállományokat - amelyek egyébként sorszámozottak -, mindenképpen le kell kérdezni, ezért nem adunk jelenleg dátum intervallumot.

**Comment by pelach** [comment]
Tehát az adózó ha kíváncsi, hogy volt-e aznap nyitó vagy, hogy melyik tétel nem lett beütve vagy nem lett mondjuk a programjába kezelve akkor leül, ír egy soap lekérdezést, leszedegeti a naplóállományokat - amelyek egyébként sorszámozottak - kibontogatja őket és megnézi amire kíváncsi.
Magát a naplóállományokat se tudja, csak ha lekérdezi külön AP szerint mi ment be az adott AP-s pénztárgépből.
De mivel bármikor mehet egy ilyen állomány (Ugye nem csak záráskor) még ki se tudja számolni, hogy mondjuk most a 1546. volt akkor tegnapelőtt a 1544.-et kell kibontania.
Egyszóval, nekem az összes AP-s beküldött naplóállományt lehetőség szerint tárolnom kell majd kibontani, hogy az adózó oldalán valóban releváns adatokat tudjak szolgálni. (Úgymint blokkszám alapján való lekérdezés vagy idő alapján való lekérdezés stb)

**Comment by renced42** [comment]
Kedves @pelach a naplóállományokhoz az adózók  eddig is hozzá juthattak a pénztárgépekből ha akartak. 
Az interfész célja, hogy általános megoldást kapjanak az adózók az adataik visszanyerésére, mert ez pénztárgépenként eltérő. Ezt a megoldást pedig ki ki a saját üzleti folyamataiba beépítheti. Ez nagyon hasonló szemlélet, mint az online számla esetében. Ott is van bizonylat és nem az XML-t nézegeti az adózó, hanem a szoftvere előállítja, megmutatja és összesíti a szükséges információt.

**Comment by renced42** [comment]
Kedves @pelach 
Zárom az issuet, ha nincs több kérdés.
