### ISSUE TITLE
[Q&A] Visszáru és sztornó bizonylatok

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Cash-Register-Logfile#21]
A rendeletben és a séma szerint a visszáru és sztornó bizonylatok `VBN > VDB`, `SZN > SBN` elemében található a visszáruzott ill. sztornózott bizonylat száma (azonosítója). A tesztfájlban az eredeti és visszáru / sztornó bizonylatok számozása valahogy nincs összhangban.

Az eredeti bizonylatok száma a következők szerint képzendő:

Nyugta (`NYN > NSZ`):
_a bizonylat száma bbbb/ccccc formátumban, ahol bbbb: adóügyi nap sorszáma ccccc: adott napon kibocsátott bizonylat sorszáma_ `<xsd:pattern value="[0-9]{4}/[0-9]{5}"/>`

Egyszerűsített számla (`ESN > IID`):
_n/aaaaaaaaa/bbbb/ccccc formátumban, ahol n: kétvállalkozós pénztárgép esetén az üzemeltető jele (A vagy B) aaaaaaaaa: AP szám bbbb: adóügyi nap sorszáma ccccc: egyszerűsített számla napi számlálója_
`<xsd:pattern value="([A-Z|0][0-9]{8}/[0-9]{4}/[0-9]{5})|([A|B]/[A-Z|0][0-9]{8}/[0-9]{4}/[0-9]{5})"/>`

Fentiek alapján hogyan lehetséges, hogy a tesztállományban a sztornó és visszáru bizonylatok a következőképpen hivatkoznak az eredeti bizonylatra:

`SZN > SBN` (a sztornózott nyugta, egyszerűsített számla vagy visszáru bizonylat egyedi azonosítója):
pl.: `<sbn>SZ/A00000001/0018/00009</sbn>`
Az egyedi azonosító nem lehet ez. Az "`SZ/`" nyilván számlára utal, de sehol semmilyen specifikációban nem szerepel, 

vagy

`VBN > VDB`
pl.: `<vdb>NY/A00000001/0018/00008</vdb>`
Az egyedi azonosító nem lehet ez. Az "`NY/`" nyilván nyugtára utal, de sehol semmilyen specifikációban nem szerepel. Ráadásul nyugta esetében nem is felelhet meg a nyugtaszámra vonatkozó `<xsd:pattern value="[0-9]{4}/[0-9]{5}"/>` megkötésnek sem, mivel abban az AP szám nem szerepel.

"`SZ`" és "`NY`" -ről egyedül a 9. mellékletben (bizonylatok mintája) van szó. Ezen kívül a 8. mellékletben találhatunk ilyet, de csak rövidítésként (ráadásul nem SZ, hanem ESZ)

Kérdésem a fent leírt "`SZ`" illetve "`NY`" előtag a sztornó illetve visszáru bizonylatok esetében mennyire általános, meg lehet-e bízni, abban, hogy ezek minden egyes pénztárgépben ott vannak. Csupán azért érdekes, mert az egyszerűsített számlákról a napi forgalmi jelentésben (`NFN`) nincs gyűjtőnkénti összesítés, így azt nyilván ki kell bányászni az összes adatból. Azonban ha a sztornó és visszáru bizonylatokból nem állapítható meg egyértelműen, hogy nyugtáról vagy egyszerűsített számláról van szó, akkor gyakorlatilag az egész pénztárgépes lekérdezés adatai csak korlátozottan használhatók.

**Comment by renced42** [comment]
Kedves @pigator 

A 48/2013. (XI. 15.) NGM rendelet 9. melléklete – ami a pénztárgéppel kiállítható egyes bizonylatok mintáját tartalmazza – az F) pontban a sztornó bizonylatra vonatkozóan, a G) pontban pedig a visszáru bizonylatra vonatkozóan írja elő, hogy ha az eredeti – vagyis a sztornózott vagy visszáruzott – értékesítési bizonylat típusa nyugta, akkor „NY”, ha egyszerűsített számla, akkor „SZ” típusjelet kell nyomtatni.

 

Ennek az előírásnak megfelelően a pénztárgépek a sztornó/visszáru bizonylaton az eredeti bizonylat számát – kezdő karakterként – kiegészítik egy „NY” vagy „SZ” jelöléssel, ami alapján egyértelműen azonosítható, hogy az eredeti bizonylat nyugta vagy egyszerűsített számla volt.

 

Szintén az egyértelmű és egyedi azonosítást szolgálja, hogy – ahogy az jogszabály szerinti bizonylatmintán is szerepel – a sztornó/visszáru bizonylaton az eredeti bizonylat száma mindig tartalmazza az eredeti bizonylatot kiállító pénztárgép AP számát is. (A nyugta bizonylatszámában az AP szám eredetileg nem szerepel, de ha visszáru/sztornó bizonylaton hivatkoznak a nyugtára, akkor az azonosíthatóság érdekében már igen.)

 

Ennek megfelelően a sztornó/visszáru bizonylaton hivatkozott eredeti bizonylatszám az alábbiak szerint épül fel a kiállított bizonylaton:

-        Nyugta esetén: NY/aaaaaaaaa/bbbb/ccccc

Az „NY” a nyugta jele, az „aaaaaaaaa” a sztornózott nyugta szerinti AP szám, a „bbbb/cccccc” pedig a sztornózott nyugta bizonylatszáma.
 
-        Egyszerűsített számla esetén: SZ/aaaaaaaaa/bbbb/ccccc
 
Az „SZ” az egyszerűsített számla jele, az „aaaaaaaaa/bbbb/ccccc” pedig a sztornózott egyszerűsített számla számlaszáma.

 
Az eredeti bizonylat számát naplózni is ennek megfelelően kell (<SBN> vagy <VDB> mezőben), ahogy a kiállított bizonylaton is szerepel. A legtöbb pénztárgépen ez így is történik, de találkoztunk már olyan esettel, ahol például hiányzott az „NY” vagy „SZ” jelölés, ugyanis a séma szerint ez is valid.

**Comment by pigator** [comment]
Kedves @renced42!
Amiket leírtál, azokat olvastam. Ugyanakkor a rendelet csak annyit ír, hogy mit kell **nyomtatni** a bizonylatra, arra viszont nem tér ki, hogy ténylegesen mit kell **tárolni** a naplófájlban ezzel kapcsolatban. Egyetlen helyen van az "SZ" és "NY" tematikáról szó,  erről szó, az általad is és általam is hivatkozott 9. mellékletben.
Sajnos csak fenntartással tudtam ezeket a nyomtatási képeket kezelni, mivel a B), F) és G) pontokban szereplő minták alapból hibásak, mivel a rajtuk szereplő bizonylatszámok esetében az AP szám (`123456789`) nem felel meg a séma által is megkövetelt `[A-Z|0][0-9]{8}` mintának.
Ahogy Te is írod:
_A legtöbb pénztárgépen ez így is történik, de találkoztunk már olyan esettel, ahol például hiányzott az „NY” vagy „SZ” jelölés, ugyanis a séma szerint ez is valid._
Tehát kétségeim nem alaptalanok. A tesztadatokból kiindulva nem lehet univerzális megoldást készíteni sztornózott / visszáruzott egyszerűsített számlák esetére, csak minden egyes konkrét pénztárgép naplófájljának ismeretében. Ez elég nagy baj.

**Comment by renced42** [comment]
Kedves @pigator A minden olyan információ ami a nyomtatott bizonylaton van annak a naplóállományban is szerepelnie kell. Ezt nagyon szigorúan ellenőrzi az engedélyező hatóság.
A vonatkozó rendelet 3. melléklet FD) Adóügyi Ellenőrző Egység (AEE) fejezet 4.d szerint:
_"A nyugta vagy egyszerűsített számla adatai között az AEE vonatkozó bejegyzésében minden olyan adatot
rögzíteni kell, ami a nyomtatott bizonylaton szerepel, kivéve a minden bizonylaton egységesen szereplő
szövegrészeket."_

**Comment by pigator** [comment]
Kedves @renced42 
nem kötözködésből, de te magad írtad:
_de találkoztunk már olyan esettel, ahol például hiányzott az „NY” vagy „SZ” jelölés, ugyanis a séma szerint ez is valid._
Ugyanakkor a rendeletben pl. SBN esetében:
_a sztornózott nyugta, egyszerűsített számla vagy visszáru bizonylat egyedi azonosítója_
Ha egy egyedi azonosítóhoz hozzáfűzök bármit (SZ, NY, KISCICA, stb., nyugta esetében még az AP szám is) , akkor az már **nem** az egyedi azonosító.
Külön letöltöttem az online számla felületről egy ügyfél pénztárgépes sztornószámláját. A bizonylatszámok a következők (AP számot megváltoztattam):
sztornó: `A12345678/S/0291/00001`, sztornózott: **`A12345678/0291/00135`**
Se NY, se SZ, se KISCICA, azonban valóban az eredeti bizonylat egyedi azonosítója! (Bár ugye azt nem tudhatjuk, hogy a  pénztárgép naplófájljában van-e NY, SZ, KISCICA) Hab a tortán, hogy a sztornó bizonylat száma sem felel meg a `<xsd:pattern value="S/[0-9]{4}/[0-9]{5}|S/(A|B)/[0-9]{4}/[0-9]{5}"/>` mintának (P17 > SBS).
Értem, amiket írsz, de a feldolgozáskor nyilván nem a ténylegesen kinyomtatott bizonylatot ellenőrizzük (ekkor látnánk, hogy van-e rajta SZ, NY), hanem a rendelet és a séma szabályait figyelembe véve járunk el. Csak a rendelet említi az SZ és NY előtagot és csakis a nyomtatással összefüggésben. A sémában erről szó sincs, amint írtad is, annak alapján bármilyen érték érvényes (valid). Maga a naplófájl akár az A és B karaktert is tárolhatná, ami nyomtatásban SZ és NY lesz...
Ha ténylegesen az eredeti bizonylatszám (egyedi azonosító) szerepelne pl. az SBN-ben, akkor nem lenne semmi probléma, mivel az nyugta esetében `<xsd:pattern value="[0-9]{4}/[0-9]{5}"/>`, egyszerűsített számla esetében pedig `<xsd:pattern value="([A-Z|0][0-9]{8}/[0-9]{4}/[0-9]{5})|([A|B]/[A-Z|0][0-9]{8}/[0-9]{4}/[0-9]{5})"/>`. Sajnos a valóságban semmilyen megkötés nincs arra, hogy ténylegesen ennek a mintának kell megfelelnie a visszáru ill. sztornó bizonylatok azonosítójának. Ha nyugta esetében szépen beszúrják elé az AP számot - és amint írtad, van olyan, hogy SZ, NY szerepel benne, van, hogy nem-, akkor semmilyen módon nem lehet megkülönböztetni a sztornó nyugtát a sztornó egyszerűsített számlától (lásd a fenti "élő" pénztárgép esetében). Csak akkor lehet biztosra menni, ha minden egyes pénztárgép esetében külön megnézzük, hogy az alkotók hogyan képzelték a megoldást. (Persze lehetne minden egyes SZ és NY nélküli sztornó pénztárgépbizonylatot visszamenőlegesen a régebbi naplófájlokban keresgetni, hogy nyugta vagy számla lett sztornózva, vagy akár az online számlaadattal összehasonlítani, de ezt nem nevezném kifejezetten erőforrásbarát megoldásnak).
Az egész problematika azért lényeges, mert számomra az lenne a fő cél, hogy a csakis azok a bevételek kerüljenek feldolgozásra, amik egyébként az online számla-adatszolgáltatásból nem kérdezhetők le. Az egyszerűsített számla (és ugyanez sztornózva) lekérdezhető. Ha ezeknek az adatai benne maradnak a pénztárgépes lekérdezésben is, akkor nyilván helytelen lesz az eredmény. Megoldás lenne persze, ha az NFN tartalmazná ezeket az adatokat, de mint már többször írtam, sajnos nem ez a helyzet...

**Comment by omachtandras** [comment]
"Az egész problematika azért lényeges, mert számomra az lenne a fő cél, hogy a csakis azok a bevételek kerüljenek feldolgozásra, amik egyébként az online számla-adatszolgáltatásból nem kérdezhetők le. Az egyszerűsített számla (és ugyanez sztornózva) lekérdezhető. Ha ezeknek az adatai benne maradnak a pénztárgépes lekérdezésben is, akkor nyilván helytelen lesz az eredmény."

Csatlakozom ehhez, mi is ilyen megoldást tervezünk készíteni.

**Comment by renced42** [comment]
Kedves @pigator 

Zárom az issuet.
