### ISSUE TITLE
[Q&A] filesNotSentReason: NOT_AVAILABLE

### ISSUE THREAD

**Issue by githubuser01x** [nav-gov-hu/Online-Cash-Register-Logfile#23]
A frissítés/karbantartás óta nem működik semmi ami a múlt héten még jó volt. A kódomon nem volt változtatás.

Ma reggel, a frissítés óta először szerettem volna a generált teszt pénztárgép adatokat lekérdezni azonban ez nem sikerült. Válaszként ezt kapom: 
```
<ns3:cashRegisterFileDataResult>
<ns3:allFilesSent>false</ns3:allFilesSent>
<ns3:filesNotSentReason>NOT_AVAILABLE</ns3:filesNotSentReason>
</ns3:cashRegisterFileDataResult>
```

Amikor lekérném a státuszt akkor a válaszban nem szerepel a pénztárgép. A software tag után ez látható:
`<ns3:cashRegisterStatusResult/>`

Ekkor megpróbáltam az adott AP számra újragenerálni a fájlokat ott viszont a következő üzenetet kapom vissza:
```
<ns2:result>
</ns2:result>:errorCode>TEST_DATA_EXIST</ns2:errorCode>
<ns2:message>A kért A12345678 -ra már léteznek teszt állományok. Kérjük használja a Státusz lekérdezést</ns2:message>
</ns2:result>
```

Egy másik kérdés alatt már utaltak arra, hogy lehetséges újragenerálni a teszt állományokat, de most úgy látszik ez mégsem jó. Ekkor megpróbáltam egy másik AP számra létrehozni a teszteket és ekkor is a fent látható üzenetet kapom. Valamint az adatokat és a státuszt  lekérdezni szintén nem tudom. Nálam lehet valami probléma? A frissített dokumentációt átnéztem, elvileg minden stimmel.

**Comment by wknav** [comment]
Kedves @githubuser01x !

A hiba a NAV oldalon van, hamarosan javításra kerül. 
A javításig: ha a program azt írja ki, hogy már létezik teszt állomány, de azok mégsem kérdezhetők le, akkor másik AP számmal kell próbálkozni. Pl. az A01230123-ra vagy az A01123456-ra mennie kellene a tesztadat generálásnak.

**Comment by wknav** [comment]
Kedves @githubuser01x !

A hiba javításra került.
