### ISSUE TITLE
queryCashRegisterFile

### ISSUE THREAD

**Issue by JancsarZ** [nav-gov-hu/Online-Cash-Register-Logfile#25]
Sziasztok!

Tegnap este próbáltam egy ideje először a generált teszt állományok letöltését, és  HTTP/1.1 404 hibát kapok vissza.
Generálás ok, státusz lekérdezés ok, de a letöltésre azt kapom, hogy aszerver nem elérhető

https://api-test-onlinepenztargep.nav.gov.hu/queryCashRegisterFile/v1/queryCashRegisterFile

Mit rontok el?
Köszi

**Comment by renced42** [comment]
Kedves @JancsarZ   Biztos 404-et kapsz, ha a linket meghívom nekem 405 jön, helyesen.

**Comment by JancsarZ** [comment]
igen, SoapUI-ból is 404 volt már tegnap este is.

**Comment by JancsarZ** [comment]
Megtaláltam a hibát, az egyik tag nevét rosszul adtam meg.
cashRegisterFileDataQuery került a cashRegisterFileDataRequest helyére is.
Csak az a kérésem, hogy ilyenkor a szabványos Bad request jöjjön (400) a 404 helyett, mert nem informatív.

Köszönjük a segítségeteket! :)

**Comment by renced42** [comment]
Kedves @JancsarZ Bad request nem tud jönni, mert az URL a hibás. 
Bad request akkor tud jönni, ha  hibás a kérés szintaxisa, rosszul formázott a  post tartalma stb..

**Comment by JancsarZ** [comment]
Igen, itt pontosan ez történt, ezért írtam feljebb. Nem az URL volt helytelen, hanem a küldött request.
De megtaláltam a hibát így is, köszönöm!
