### ISSUE TITLE
Automatikus jogosultság képzés

### ISSUE THREAD

**Issue by vbela75x** [nav-gov-hu/Online-Cash-Register-Logfile#26]
Tisztelt Fejlesztők,

1. Ha a rendszer élesre fordul a jogosultságokat automatikusan ki kellene terjeszteni az OPG lekérdezésre legalább azokban az esetekben ahol nem csak a saját számlák lekérdezése van beállítva. Így rengeteg időt és telefont lehetne megspórolni mert mire a felhasználók beállítják az nem kevés idő lesz.

2. A éles adatok mikorra várhatók tartható a Q4 vége ahogy az előzetesen lett ígérve?

**Comment by blaky** [comment]
Szerintem mostmár elég Q4 vége van. Jó lenne egy update a NAV-tól, hogy tudjunk tervezni.

**Comment by vbela75x** [comment]
Kedves @renced42 

Van fejlemény az éles adatokkal kapcsolatban?

**Comment by renced42** [comment]
Kedves @vbela75x 

Jó hírem van. Szerintem heteken belül :)

**Comment by renced42** [comment]
Kedves @vbela75x 

A jogosultságokat sajnos nincs módunkban automatikusan beállítani, mint ahogy más esetben sem. Azt az ügyfeleknek szükséges megtenni.
