### ISSUE TITLE
[Q&A] Hogy áll a project?

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Cash-Register-Logfile#28]
Érdeklődöm, hogyan áll a project?
A 2022. utolsó negyedév végi éles bevezetésből nyilvánvalóan nem lett semmi. Három hónapja semmiféle kommunikáció. Néztem, hátha titokban már elindult, csak nem kötötték az orrunkra, de nem: az online számlánál a technikai felhasználónál nem lehet pénztárgépes jogosultságot adni - hacsak nincs arra egy igazán titkos felület...
Gondolom, az eleinte lelkes, majd egyre lelombozottabb érdeklődők nem kevés órát tököltek a P7B fájlokkal, NFN, PJN, ZQQ és társaikkal; ugye nem megy ez a munka a levesbe?
Van bármi esély, hogy a megkezdett évben már a januári adatokat le lehessen kérdezni?

**Comment by renced42** [comment]
Kedves @pigator ha minden terv szerint megy akkor februárban élesedik.

**Comment by renced42** [comment]
> Köszönöm. Reméljük a legjobbakat... Lehetséges lesz lekérdezni a teljes januári adatokat?

Kedves @pigator mindig az aktuális utolsó 14 nap kérdezhető le.

https://nav.gov.hu/ado/egyeb/jelentosen-megkonnyiti-a-konyvelok-dolgat-a-nav-azzal-hogy-letolthetok-az-online-penztargepek-adatai
