### ISSUE TITLE
[Q&A] Éles letöltésnél: not a valid URI?

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Cash-Register-Logfile#29]
Az eddigi tesztkörnyezetben nem kaptam ilyen jellegű hibát egyszer sem, a mai éles letöltéseknél igen:
`namespace error : xmlns:schemaLocation: 'http://schemas.nav.gov.hu/OPGN/2.0 AEEnaplo.xsd' is not a valid URI`

Itt az érintett rész. Itt valóban hiba van, vagy én bénázok?
`<ROWS xmlns="http://schemas.nav.gov.hu/OPGN/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:schemaLocation="http://schemas.nav.gov.hu/OPGN/2.0 AEEnaplo.xsd" semaver="X0006" >`

Másik pénztárgépnél jó a lekérdezés:
`<ROWS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.nav.gov.hu/OPGN/2.0 AEEnaplo.xsd" xmlns="http://schemas.nav.gov.hu/OPGN/2.0" semaver="X0006" >`

A különbség:
`xmlns:schemaLocation` vs. `xsi:schemaLocation`
Ez azt jelentené, hogy nem megfelelően szolgáltat adatot az egyik pénztárgép?

**Comment by renced42** [comment]
Kedves @pigator 

A probléma itt van: 
"xmlns:schemaLocation="http://schemas.nav.gov.hu/OPGN/2.0 AEEnaplo.xsd"

Valamelyik pénztárgép az XML-be beteszi a schemaLocation-t így az XML parser keresi az AEEnaplo.xsd-t. Ez teljesen valid.
Két lehetőség van vagy ezt a hibát ignorálod, vagy a parsernek odateszed az XSD-t.
Az AEEnaplo.xsd a hatályos kipublikált OPG napló xsd.
