### ISSUE TITLE
Biztos hogy aktuálisak a wsdl és xsd fájlok?

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Cash-Register-Logfile#3]
Mindegyik wsdl-ben és xsd-ben  "Version: v1.0 2019/11/10" comment van.

**Comment by renced42** [comment]
Kedves @EPluribusUnum igen azok, de köszi a jelzést, frissíteni fogjuk a komment részt.

**Comment by renced42** [comment]
Kedves @EPluribusUnum frissítettük a verziószámokat.
