### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by csinab** [nav-gov-hu/Online-Cash-Register-Logfile#30]
Java EE - JDK11 környezetből szerettem volna csatlakozni a https://api-test-onlinepenztargep.nav.gov.hu/queryCashRegisterFile/v1/queryCashRegisterFile végponthoz, viszont minden alkalommal a HTTP ERROR 403 hibaüzenetet kapom vissza.

Kérném segítségüket.

**Comment by wknav** [comment]
Valószínűleg a Content-Type a hibás. Ennek az értéke application/soap+xml kell legyen.

**Comment by speak82** [comment]
POST adat probléma, Content-Type hiba nekem 500 as hiba volt.

**Comment by csinab** [comment]
Köszönöm a segítséget. Mindekettő esetben hibáztam. 
Az objektum csomag amit használtam felül definiálta a Content-Type-ot, és a WSDL-ből automatikusan generált xml sem volt megfelelő.
Áttértem az alap jávás HttpURLConnection-re és kézzel állítok be mindent, és persze javítottam az xml-t is.

Most már OPERATION_FAILED hibát kapok. Hiba oka: váratlan feldolgozási hiba esetén

Leírás alapján értesítenem kellene a NAV helpdesket.

**Comment by wknav** [comment]
A teszt vagy az éles környezetben történt a próbálkozás?

**Comment by csinab** [comment]
Köszönöm a sok segítséget!
Igen a nagybetűvé alakítás megoldotta a problémám.

Már szépen érkeznek a zippelt adatok.
Márcsak ezt a ZIP + MTOM választ kell megfejtenem. :)
