### ISSUE TITLE
Hibás p7b fájlok [Q&A]

### ISSUE THREAD

**Issue by vbela75x** [nav-gov-hu/Online-Cash-Register-Logfile#32]
Kedves @renced42 ,

Hová kellene küldenem olyan fájlokat amik hibásak, milyen azonosítókkal. 
Pl.: - az xml olyan karaktereket tartalmaz váratlan helyeken amelyek nem is lehetnének a fájlba (értelmezhetetlen karakterek)
- olyan xml fájl töltődik le ami nem valid az xsd sémával.
20.515 db fájl töltöttem le a mai nap folyamán, ebből kb. 25 gépnek voltak rosszak az adatai de ott minden fájl ami a géphez tartozik és kb 8-10 típust érint a dolog.

**Comment by renced42** [comment]
Kedves @vbela75x 

Alapvetően sehova, mivel adótitkot képez a tartalma.
Leggyosabban a pénztárgép forgalmazóval lehet felvnni a kapcsolatot,  Specifikáción is ezt írtuk.
A letöltésnél a fileValidationResultCode tag tartalmazza a file ellenőrzés eredményét.
