### ISSUE TITLE
Milyen xsd verziók használhatók az AAEnaplo - ra?[Q&A]

### ISSUE THREAD

**Issue by vbela75x** [nav-gov-hu/Online-Cash-Register-Logfile#33]
Találkoztam olyan gépekkel amelyek 1.0 verzióval töltenek fel adatokat ez lehetséges?
Nem csak a 2.0 használható.

![image](https://user-images.githubusercontent.com/92086715/218259372-b7672a52-bae5-4574-a4eb-b473c403145b.png)

**Comment by omachtandras** [comment]
@vbela75x : szerintem simán lehet. Amikor bevezette a NAV azt a megoldást, hogy a pénztárgéppel kiállított számlák megjelentek az Online számában, akkor több helyről jelezték nálunk, hogy bizonyos partnerek ilyen számlái nem látszanak. NAVos kollégákkal levelezve kiderült, hogy a "régi" pénztárgép szoftver változatok -, amelyek nem is lehetnének már forgalomban - által előállított naplófájlokból nem tudnak konvertálni az online számlába.
Akkor mi azt csináltuk, hogy elkezdtük megkeresni a számlakiállítókat, hogy cseréljék/cseréltessék a gépeiken a szoftvert, mert nem felelnek meg a törvényeknek. Jellemzően nagy értetlenkedés volt, de aztán néhány kör után mindenhol megértették a problémát és a cserék mentek is. Egy ideje már nem foglalkozunk ezzel, a számla befogadóknak mondjuk, hogy vegyék fel a kiállítóval a kapcsolatot, végül is az ő érdekük, hogy be tudják fogadni a számlát adatrögzítés nélkül/minimális plusz adat megadásával...
Akkor egyébként a NAVosoknak volt egy félmondata, hogy csinálnak egy lekérdezést és értesítik az ilyen pénztárgép verziót használó adózókat, nem tudom ebből lett-e valami, vagy az élet elsodorta magával a gondolatot... :)

**Comment by renced42** [comment]
Kedves @vbela75x 

Igen leheséges.

A jelenlegi szabályoszás alapján még régi 1.0-s pénztárgépek is működhetnek. Tehát forgalomban ugyan nincsennek, mert nem értékesíthetők, de használhatók. Ezek egyre kevesebben vannak.

Megnézem, hogy ezekhez milyen XSD volt annó kipublikálva és kiteszem a repoba.

@omachtandras Sajnos hiába csinálunk ilyen lekérdezést nem kötelezheti a NAV a régi típusú PTG lecserélésére az adózót.
Ha van olyan engedélyszám ahol a PTG szoftver esetében van 2.0-s verzió ott lehet frissíteni a PTG-t az új verzióra, de ott is vannk esetek, ahol ezt nem feltétlenül lehet megvalósítani.

**Comment by omachtandras** [comment]
@renced42 : nem vagyok képben nagyon a pénztárgépekkel, de mintha valami olyan "hangzott" volna el, hogy olyan gép lehet már csak használatban, amelynek van 2.0(?) verziót támogató szoftvere is és arra kell frissíteni.
(Visszakerestem: "Nem, az engedélyük nincs visszavonva. Ők időben frissítették az engedélyt, csak utána nem telepítették le az új verziót. Szóval mulasztásban vannak, de nem úgy. ")
Ebből értettem én ki azt, hogy MINDENKINEK 2.0-ra kell frissíteni, bár nézve a levelezést valóban konkrét típusról volt szó és annak van 2.0-s változata is, ezért tudtak frissíteni, és így utólag már értem, hogy csak azoknak kell(ene), akiknek a gépe megszerezte ezt az engedélyt is.

De mindegy is, akkor az adott eladókkal kapcsolatban megoldódott a dolog, sikerült egyeztetni a pénztárgépet használókkal, hogy frissítsenek.

Most meg még jobb a helyzet, mert ha valaki ezt az interface-t akarja használni, akkor az azt jelenti, hogy a pénztárgép az övé, Márpedig ha az övé, akkor tud tenni a probléma ellen, ha az fontossá vált számára is.

**Comment by vbela75x** [comment]
@renced42 : Akkor várom a 1.0 xsd figyelem a feltöltést. 940 db gépet töltök jelenleg ebből 30 db volt 1.0-as.
