### ISSUE TITLE
[Q&A] a kapott file formátuma

### ISSUE THREAD

**Issue by PongraczIstvan** [nav-gov-hu/Online-Cash-Register-Logfile#34]
A dokumentációban a következő módon szerepel a kapott file-ok formátuma:

"A P7B állományok tömörített formában kerülnek továbbításra, a naplóállományok méretétől 
függetlenül. A tömörítés ZIP formátumban történik."

A lekérdezett adatok - hexaeditorba betöltve - valóban ZIP állománynak tűnnek, de ha ezeket lementem file-ba, akkor megnyitáskor a következő hibát kapom (több programmal is kipróbáltam):

"Az archívum ismeretlen vagy sérült"

Programkódban - Chilkat dll-t használva -  szintén sikertelen a megnyitás:

- failed to read the zip file comment
- failed to get central dir locations

Mi lehet a gond?

**Comment by renced42** [comment]
Kedves @PongraczIstvan 

Éppen válaszolni akartam de látom zártad az Issue-t.
Mi volt a problémára a megoldás?

**Comment by PongraczIstvan** [comment]
> Kedves @PongraczIstvan
> 
> Éppen válaszolni akartam de látom zártad az Issue-t. Mi volt a problémára a megoldás?

Sajnos még nem sikerült megoldani ezt a gondot, de eszembe jutott még egy két dolog, amit ki akartam próbálni. 

Eddig a Delphi TRest osztályát használtam Api-k lekérdezéshez, de az sajnos nem támogatja - vagy eddig nem jöttem rá hogyan - a bineáris adatokat. Szóval a response üresen jött vissza, mert mindenáron kódolni akart :( Így néznem kellett valami "kütyüt" ami támogatja

**Comment by PongraczIstvan** [comment]
Kedves @renced42 !

Hogy a lehetséges hibákat kiszűrjem letöltöttem  a sample könyvtárból a queryCashRegisterFileDataResponse.data és a queryCashRegisterFileDataResponse2.data file-okat. Az ezekben található adatokat minden gond nélkül fel tudtam dolgozni. A generált zip file-okat mind a windows, mind a winrar szépen fel tudta olvasni, tudta kezelni.  

Sajnos az általam lekért cég adatainál továbbra is fennáll a kezdeti hiba. :(

**Comment by erikapapp** [comment]
Kedves @renced42!

Én is a `QueryCashRegisterFileDataResponse` feldolgozásán dolgozom. 

```
------=_Part_10220_1432721102.1676293389926
Content-Type: application/octet-stream
Content-ID: <f85ddcd9-d08e-4026-926a-0a16c4a0698e@schemas.nav.gov.hu>
Content-Transfer-Encoding: binary

PKL>V)A87654321_12345678_20230130013620_531.p7b\x9dZm\x8c\Wy\xce\xda&4\xb7%\xad@\xa0\x8ed\xacU\xdb\xcc\xee\xf9\xfeX\xaeoz\xee\xf9\xf0\xaewwv\xbd3\xde\xc4[w\xb3;\x8e\x9d]\xe3\xdd8\x8e\x91&\xc4\xaa\xd2B%@rDK+
.....
\xd5\xb7/\xfe\xe9}\xe3o\xbes\xf5\xef^\xa5\x9f\xfb`\xb9\xf2\x83\xd7^\xff\xd1\xbf\xbe"|\xc3\xfd\xd9\xf8\xd2\xd4\xffPK=\xfb\x93\xe3\xf3K%PKL>V=\xfb\x93\xe3\xf3K%)A87654321_12345678_20230130013620_531.p7bPKWJ
------=_Part_10220_1432721102.1676293389926
```

A leírás alapján "A pénztárgép által beküldött naplóállomány GZIP által tömörített formában." azonban nekem  a "`PKL>`" kezdetű és "`PKWJ`" végű tartalomra azt írja hogy nem zippelt tartalom.

**Comment by Gyozke** [comment]
Kedves renced42 és erikapapp!

Én is hasonló problémával küzdök. A választ a curl lementi egy fájlba, de nem sikerül helyesen kivágni belőle a zip állomány részét. Talán nem jól határozzuk meg az állomány elejét vagy a végét?

Köszönöm,
Győző

**Comment by renced42** [comment]
Kedves @erikapapp @Gyozke @PongraczIstvan 

A napló file-ok ZIP-elve vannak a legjobb tudomásom szerint. (Korábban a Speciben valóban GZIP szerepelt helytelenül, de ez javítva lett).
A teszt rendszerben nem boldogultok?

**Comment by PongraczIstvan** [comment]
Kedves @renced42 !

A sample-ben megadott response állományok  formátuma nem egyezik meg a most visszakapott formátummal? (Mert akkor korán örültem a félsikernek, amit az előzőleg írtam ;) ) 
Esetleg a teszt rendszerben más algoritmus dolgozik?

**Comment by Gyozke** [comment]
A gondom a response.xml-ből történő kivágással van. Melyik pozíciótol kezdődik és hol fejeződik be a zip állomány?

**Comment by Gyozke** [comment]
> 

Én a hex editor neoval próbálkoztam, és azzal skerült az éles állományból kivágnom a zip fájlt, ami működik.

**Comment by PongraczIstvan** [comment]
... és mi volt a titok? Nekem sajna még mindig nem megy:( A sample állománnyal tökéletes, a letöltött élessel nem.

**Comment by Gyozke** [comment]
A hex editor neoval kimásoltam a PK-val kezdődő részt egészen az elválasztó részt jelőlő kötőjelig. A kijelőlés a P-betűvel kezdődik, a vége pedig az első kötőjelet megelőző byte-ig tart. Ezt kimásolva az éles rendszerből kapott válaszból is helyes zip fájl képződik. Más kérdés ennek a kódolása...

**Comment by Gyozke** [comment]
Hol található specifikációt az AEE xml állományhoz?

**Comment by PongraczIstvan** [comment]
[https://net.jogtar.hu/jogszabaly?docid=a1300048.ngm](https://net.jogtar.hu/jogszabaly?docid=a1300048.ngm) 4. melléklet

**Comment by renced42** [comment]
> A p7b file-ok validálása sikerült valakinek?
Azt nem fogod tudni validálni, mert nincs meg nálad az az infó.

**Comment by PongraczIstvan** [comment]
Milyen infóra gondolsz?
 A digitális aláírásnak az a lényege, hogy tartalmazza a hash visszakódolásához szükséges public kódot. Ha ez nincs meg vagy a tanúsítvány kiállítója nem megbízható (azonosítható), akkor az nem aláírás, hisz pont a dolog lényege vész el!
 Úgy gondolom, hogy ezt a lekérdezést  olyanok fogják használni, akik valamely' könyvelő szoftverbe akarják automatikusan betölteni az adatokat, de ha nem lehet hitelesnek elfogadni ...
