### ISSUE TITLE
Előfordulhat OPGN/1.0 ?

### ISSUE THREAD

**Issue by jsz66** [nav-gov-hu/Online-Cash-Register-Logfile#35]
Működhet még olyan pénztárgép (van, mert tapasztalom), amelyik még a korábbi xsd szerint tölti fel a naplóállományokat?

 xmlns="http://schemas.nav.gov.hu/OPGN/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:schemaLocation="http://schemas.nav.gov.hu/OPGN/1.0 AEEnaplo.xsd" semaver="v5"

Lehet, hogy az én figyelmetlenségem, de sem a tesztadatokban, sem a leírásokban nem találkoztam ezzel a "lehetőséggel". Azt látom, hogy közzé lett téve néhány napja a "V1_AEEnaplo_V4_0917_2013.09.18_08_42.xsd".

**Comment by omachtandras** [comment]
@jsz66 : elő.  https://github.com/nav-gov-hu/Online-Cash-Register-Logfile/issues/33

**Comment by jsz66** [comment]
Erről csak én nem találtam a rendelkezésre álló anyagok között erre való utalást és jogosan csodálkozom rá? A tesztoldalról letölthető generált napló állományok alapján végzett fejlesztést tekintsem bemelegítésnek és készüljek további meglepetésekre?

**Comment by renced42** [comment]
Kedves @jsz66 

Köszönjük  az észrevételt. Valóban a teszt adatok esetén nem generálunk V1-es pénztárgép adatokat. A pénztárgépek vonatkozó jogszabályhoz kapcsolódóan küldik az adatokat. A jogszabály szerint még működhetnek ilyen pénztárgépek. A specifikációban erre ezért nem is tértünk ki, de az észrevétel alapján pontosítjuk a szöveget.

**Comment by jsz66** [comment]
Köszönöm a tájékoztatást!
