### ISSUE TITLE
A válaszban kapott zip file sérült [Q&A]

### ISSUE THREAD

**Issue by MoroZoltan** [nav-gov-hu/Online-Cash-Register-Logfile#36]
A leírások alapján visszakapom a választ amiből kiemelem a "PK"-val kezdődő és a következő '-----' tartó részt (az előző itteni kérdések válaszai alapján)
A kapott fileok  közül egy sem csomagolható ki 6 pénztárgép alapján.
Hibák:(teljesen váltózó nem gépenként azonos a válasz)
-zip file sérült még a benne lévő file sem látható. 
-zip ben látható a p7b nevű file, mérete látszik de a létrehozás ideje hiányzik
-zip ben benne a p7b nevű file métet létrehozás ideje is látszik.

Kicsomagolás javítás semmilyen programmal nem lehetséges.

Kérdésem az lenne milyen megoldással nyerhető ki a tartalom?

**Comment by wknav** [comment]
Kedves @MoroZoltan !

Első körben érdemes pl. SoapUI eszközzel megpróbálni az állományok lekérdezését.
A SoapUI a letöltött fájlokat külön attachment-ként jeleníti meg, és azokat külön le lehet menteni.

**Comment by MoroZoltan** [comment]
Köszönöm az információt a lekérdezés már ment.
Megnéztem SOAPUI ban is így össze tudtam hasonlítani az adatokat.
Filestream ban próbáltam menteni úgy hibás volt, átváltottam memorystreamra és onnan mentésre és ez megoldotta a problémát és már helyes adatok jönnek le.

Köszönöm.
