### ISSUE TITLE
Csatlakozási probléma

### ISSUE THREAD

**Issue by apsbalazs** [nav-gov-hu/Online-Cash-Register-Logfile#37]
.Net környezetben HttpWebRequest kéréssel szerettem volna csatlakozni a : 
https://api-onlinepenztargep.nav.gov.hu/queryCashRegisterFile/v1/queryCashRegisterStatus végponthoz 
(action: queryCashRegisterStatus,
request.ContentType = "application/soap+xml;charset=\"utf-8\"";
request.Accept = "application/soap+xml";)
de 500-as belső kiszolgáló hibaüzenetet kapok vissza.
Mi lehet a probléma?

**Comment by renced42** [comment]
Kedves @apsbalazs 

Teszt környezetben sikerült már a kapcsolódás?

**Comment by apsbalazs** [comment]
Nem, rögtön az élesben próbálom.
ez volt a kérés:
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:api="http://schemas.nav.gov.hu/OPF/1.0/api"
	xmlns:com="http://schemas.nav.gov.hu/NTCA/1.0/common">
	<soap:Header />
	<soap:Body>
		<api:QueryCashRegisterStatusRequest>
			<soap:header>
				<com:requestId>45415115022023202807</com:requestId>
				<com:timestamp>2023-02-15T19:28:07.260Z</com:timestamp>
				<com:requestVersion>1.0</com:requestVersion>
				<com:headerVersion>1.0</com:headerVersion>
			</soap:header>
			<com:user>
				<com:login>xxxxxxx</com:login>
				<com:passwordHash cryptoType="SHA-512">0B39AE13AC78ED33CEA16A87D42A636EC7A4A5FEC29EC4273A21D477A07F735FB2752556246B74C28D4E168D4F0D9AB1EC2375A1660BB999C9DEB0C14AE5C632</com:passwordHash>
				<com:taxNumber>xxxxx</com:taxNumber>
				<com:requestSignature cryptoType="SHA3-512">3E270972B2FB2FA9D07EDDBD906FC312256CF027F3D805204939A4382B7625F74169F7730EEF88661F3B2FFD079DFB2083696D08E7A94B2D6D2896C9BC7BF9B2</com:requestSignature>
			</com:user>
			<api:software>
				<api:softwareId>HU1238885700000001</api:softwareId>
				<api:softwareName>DataIndex</api:softwareName>
				<api:softwareOperation>LOCAL_SOFTWARE</api:softwareOperation>
				<api:softwareMainVersion>1.1</api:softwareMainVersion>
				<api:softwareDevName>Balázs Péter</api:softwareDevName>
				<api:softwareDevContact>balazs.peter@dataindex.hu</api:softwareDevContact>
				<api:softwareDevCountryCode>HU</api:softwareDevCountryCode>
				<api:softwareDevTaxNumber>12388857</api:softwareDevTaxNumber>
			</api:software>
			<api:cashRegisterStatusQuery>
				<api:APNumberList>
					<api:APNumber>xxxxxxxx</api:APNumber>
				</api:APNumberList>
			</api:cashRegisterStatusQuery>
		</api:QueryCashRegisterStatusRequest>
	</soap:Body>
</soap:Envelope>

**Comment by renced42** [comment]
Kedves  @apsbalazs

Javaslom, hogy ne az éles rendszeren próbálkozz, első körben hanem a teszten. Gondolom , a megfelelő jogosultság a technikai felhasználónak be van állítva, ha nincs akkor azt is meg kell csinálni.

**Comment by apsbalazs** [comment]
A jogosultsággal nincs probléma. A NAV online számla szépen működik, a pénztárgép használat hozzá van adva a technikai felhasználóhoz. A teszt környezetbe is az 500-as hibakódot kapom vissza.

**Comment by renced42** [comment]
Kedves @apsbalazs akkor a teszt rendszeri request id-t dobd be és megnézzük.

**Comment by apsbalazs** [comment]
Kedves @renced42  <com:requestId>54734424022023131937</com:requestId>

**Comment by wknav** [comment]
Kedves @apsbalazs !

A kérésben a header résznek rossz a namespace-e, soap:header szerepel com:header helyett:
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:api="http://schemas.nav.gov.hu/OPF/1.0/api"
xmlns:com="[http://schemas.nav.gov.hu/NTCA/1.0/common">](http://schemas.nav.gov.hu/NTCA/1.0/common%22%3E)
<soap:Header />
soap:Body
api:QueryCashRegisterStatusRequest
soap:header <-- **Itt com:header kellene**
com:requestId45415115022023202807</com:requestId>
com:timestamp2023-02-15T19:28:07.260Z</com:timestamp>
com:requestVersion1.0</com:requestVersion>
com:headerVersion1.0</com:headerVersion>
</soap:header>  <-- **Itt /com:header kellene**

**Comment by apsbalazs** [comment]
Kedves @wknav köszönöm a segítséget. Ez volt a probléma.
