### ISSUE TITLE
403 Forbidden hiba[Q&A]

### ISSUE THREAD

**Issue by DDarida** [nav-gov-hu/Online-Cash-Register-Logfile#38]
Teszt környezetben a https://api-test-onlinepenztargep.nav.gov.hu/queryCashRegisterFile/v1/queryCashRegister végpontra az alábbi kérést küldöm POST methodussal. Próbáltam POSTMAN programból, próbáltam C# .Net Framework progam HTTPClient, és HttpRequestMessage segítségével, de minden esetben 403 Forbidden hibát kapok.
Ugyanez a helyzet ha éles környezetre küldök kérést. Kérem segítsenek megtalálni a hiba okát, hogy mit rontok el.

`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:api="http://schemas.nav.gov.hu/OPF/1.0/api" xmlns:com="http://schemas.nav.gov.hu/NTCA/1.0/common">
    <soap:Header/>
    <soap:Body>
        <QueryCashRegisterFileDataRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <header xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
                <requestId>SAX7Gqn9FES8Zw2WvQmy3A</requestId>
                <timestamp>2023-02-27T11:32:06.017Z</timestamp>
                <requestVersion>1.0</requestVersion>
                <headerVersion>1.0</headerVersion>
            </header>
            <user xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
                <login>pnryvxy0lmebwb2</login>
                <passwordHash cryptoType="SHA-512">C758F8B2CDA03ABC690932CA6ADBB9A792C8226925556962EAB220FC5C59C09BB9A025A6E80178AE17D9B81C208B2F667952E26CFD9E47D9F44C46EDD1F28B62</passwordHash>
                <taxNumber>46589637</taxNumber>
                <requestSignature cryptoType="SHA3-512">76D72B30BCB1ED6BBBFBCBD6D30A4975FEA7FFCE2750FCE4DCCF444C45E3E37FDE6B0A02A8D8D7D30BFF74E4151E7E680678CFEA5CF5C38AAB584B584E687D84</requestSignature>
            </user>
            <software xmlns="http://schemas.nav.gov.hu/OPF/1.0/api">
                <softwareId>HU703192-DEEP-0100</softwareId>
                <softwareName>deep.erp</softwareName>
                <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
                <softwareMainVersion>1.0</softwareMainVersion>
                <softwareDevName>Revolution</softwareDevName>
                <softwareDevContact>deepuzletag@revolution.hu</softwareDevContact>
                <softwareDevCountryCode>HU</softwareDevCountryCode>
                <softwareDevTaxNumber />
            </software>
            <cashRegisterFileDataQuery xmlns="http://schemas.nav.gov.hu/OPF/1.0/api">
                <APNumber>A19720225</APNumber>
                <fileNumberStart>1</fileNumberStart>
                <fileNumberEnd>1</fileNumberEnd>
            </cashRegisterFileDataQuery>
        </QueryCashRegisterFileDataRequest>
    </soap:Body>
</soap:Envelope>`

**Comment by wknav** [comment]
Kedves @DDarida !

A következő hibákat látom:
- A helyes url a következő: https://api-test-onlinepenztargep.nav.gov.hu/queryCashRegisterFile/v1/queryCashRegisterFile
- A kérésben hiányzik a QueryCashRegisterFileDataRequest namespace-e (ezt most beletettem), illetve hiányik a softwareDevTaxNumber adat (Megjegyzés: valamiért a github most nem akar félkövér karaktereket megjeleníteni, így ezek a részek a kérésben **-al vannak jelölve):
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:api="http://schemas.nav.gov.hu/OPF/1.0/api" xmlns:com="http://schemas.nav.gov.hu/NTCA/1.0/common">
   <soap:Header/>
   <soap:Body>
      <QueryCashRegisterFileDataRequest **xmlns="http://schemas.nav.gov.hu/OPF/1.0/api"** xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <header xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
            <requestId>SAX7Gqn9FES8Zw2WvQmy3A</requestId>
            <timestamp>2023-02-27T11:32:06.017Z</timestamp>
            <requestVersion>1.0</requestVersion>
            <headerVersion>1.0</headerVersion>
         </header>
         <user xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
            <login>pnryvxy0lmebwb2</login>
            <passwordHash cryptoType="SHA-512">C758F8B2CDA03ABC690932CA6ADBB9A792C8226925556962EAB220FC5C59C09BB9A025A6E80178AE17D9B81C208B2F667952E26CFD9E47D9F44C46EDD1F28B62</passwordHash>
            <taxNumber>46589637</taxNumber>
            <requestSignature cryptoType="SHA3-512">76D72B30BCB1ED6BBBFBCBD6D30A4975FEA7FFCE2750FCE4DCCF444C45E3E37FDE6B0A02A8D8D7D30BFF74E4151E7E680678CFEA5CF5C38AAB584B584E687D84</requestSignature>
         </user>
         <software xmlns="http://schemas.nav.gov.hu/OPF/1.0/api">
            <softwareId>HU703192-DEEP-0100</softwareId>
            <softwareName>deep.erp</softwareName>
            <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
            <softwareMainVersion>1.0</softwareMainVersion>
            <softwareDevName>Revolution</softwareDevName>
            <softwareDevContact>deepuzletag@revolution.hu</softwareDevContact>
            <softwareDevCountryCode>HU</softwareDevCountryCode>
            **<softwareDevTaxNumber/>**
         </software>
         <cashRegisterFileDataQuery xmlns="http://schemas.nav.gov.hu/OPF/1.0/api">
            <APNumber>A19720225</APNumber>
            <fileNumberStart>1</fileNumberStart>
            <fileNumberEnd>1</fileNumberEnd>
         </cashRegisterFileDataQuery>
      </QueryCashRegisterFileDataRequest>
   </soap:Body>
</soap:Envelope>
```

**Comment by DDarida** [comment]
Köszönöm a segítséget, így már megy a kérés.
