### ISSUE TITLE
P7B xsd

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Cash-Register-Logfile#4]
Jó lenne ha itt is publikálva lenne.

1 óra Google után sem találtam meg a fájlt. Hol érhető el?
Ennyit találtam, de link sehol...

"4. melléklet a 48/2013. (XI. 15.) NGM rendelethez.

1. Az AEE-nek a pénztárgépben keletkezett adatokat UTF-8-as kódlap szerinti
karakterkódolású, XML típusú naplóállományokban kell tárolnia. Az állomány
struktúrájának leírását és a séma ellenőrző állományt (XSD állomány) a NAV
közleményben teszi közzé.”

Köszönöm.

**Comment by codeisthelaw429** [comment]
A NAV honlapján [innen](https://nav.gov.hu/ado/onlinepenztargepek_1417761437385/Kozlemeny_az_onlinepe20210126) (Kapcsolódó anyagok) letölhető az XSD 6.6.5-ös verziója.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
Feltettem ide: https://github.com/nav-gov-hu/Online-Cash-Register-Logfile/tree/master/src/schemas/nav/gov/hu/OPG
