### ISSUE TITLE
Teszt adat generálás Delphiből

### ISSUE THREAD

**Issue by migpeti** [nav-gov-hu/Online-Cash-Register-Logfile#40]
Nem tudok rájönni, hogy miért, de folyamatosan 500-as státuszú hibát kapok.

A Kérés:
`<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SOAP-ENV:Body>
		<GenerateCashRegisterTestDataRequest xmlns="http://schemas.nav.gov.hu/OPF/1.0/api">
			<header xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
				<requestId>1653972432E4E9C78B46119FF41708</requestId>
				<timestamp>2023-02-27T18:57:34.000Z</timestamp>
				<requestVersion>1.0</requestVersion>
				<headerVersion>1.0</headerVersion>
			</header>
			<user xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
				<login>jRK7TXu5WN4y0G4</login>
				<passwordHash cryptoType="SHA-512">F67B926F3FA60D7000D8EB1EFD0C80C0BEBA3FF3093547865CB47311A102BF75C550D1334AF5E9930A6095BC1BBE2F6F46D51F3EED38E9F24DF0AE2BC0BA6956</passwordHash>
				<taxNumber>10426917</taxNumber>
				<requestSignature cryptoType="SHA3-512">7E2648EC8E826437FA5CD60A6142115152BA3420990A60DF887263DB81460089CA3533BCDEBE1E44EEAC7119D0A10C8595B8AC3C8EFB672F5F85FC428C6967B2</requestSignature>
			</user>
			<software>
				<softwareId>HOSTWAREFOK7-20TST</softwareId>
				<softwareName>Főkönyvi könyvelés programcsomag (debug verzió)</softwareName>
				<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
				<softwareMainVersion>7.20</softwareMainVersion>
				<softwareDevName>HostWare Kft.</softwareDevName>
				<softwareDevContact>hostware@hostware.hu</softwareDevContact>
				<softwareDevCountryCode>HU</softwareDevCountryCode>
				<softwareDevTaxNumber>10426917</softwareDevTaxNumber>
			</software>
			<generateCashRegisterTestDataParameter>
				<APNumber>A10204242</APNumber>
			</generateCashRegisterTestDataParameter>
		</GenerateCashRegisterTestDataRequest>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

A válasz pedig folyamatosan:
{"timestamp":"2023-02-27T19:06:26.469+0000","status":500,"error":"Internal Server Error","message":"Could not create message from InputStream: Unable to internalize message; nested exception is com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Unable to internalize message","path":"/generateCashRegisterTestData/v1/generateCashRegisterTestData"}

**Comment by wknav** [comment]
Ellenőrizni kellene a kérésben a Content-Type-ot. A következőnek kellene lennie:
Content-Type: application/soap+xml

**Comment by wknav** [comment]
Milyen egyéb header paramétereket tartalmaz az üzenet?

**Comment by migpeti** [comment]
Köszönöm a segítséget. Valóban a content-type hiánya volt a gond. Sikerült továbblépnem. A Delphibe (XE7) beépített SOAP kezelő modul ugyan előkészítette a Request header-t, de a http kérésbe már nem került bele. Delphi fejlesztő kollégáim számára a tapasztalat: USE_INDY compiler direktívával már korrekt a http kérés. Én úgy látom, hogy ha a Winapi.WinInet.HttpSendRequest kellene, hogy küldje a kérést, akkor a header nem kerül bele.
