### ISSUE TITLE
[Q&A] SSL handshake

### ISSUE THREAD

**Issue by valyinagya** [nav-gov-hu/Online-Cash-Register-Logfile#41]
Üdvözlöm,
A teszt API-t szeretném megszólítani, ehhez szükségem lenne az útvonalhoz tartozó certficate-re.
Tudna ebben segíteni?
Előre is köszönöm!

**Comment by wknav** [comment]
Az api-test-onlinepenztargep.nav.gov.hu a NAV publikus tanúsítványát használja. A tanúsítvány kibocsátója: e-Szigno SSL CA 2014, ezt elképzelhető, hogy le kell tölteni, hogy a NAV tanúsítvány ellenőrizhető legyen (https://sslca2014-valid.e-szigno.hu/).
De az a gyanúm, hogy a meghíváskor nem ez okozza a hibát. Mi a konkrét probléma?

**Comment by valyinagya** [comment]
A konkrét hibaüzenet a következő: SRT: Processing error in Internet Communication Framework: ("SSL handshake with api-test-onlinepenztargep.nav.gov.hu:443 failed: SSSLERR_PEER_CERT_UNTRUSTED (-102)Peer's X.509 Certificate (chain) is untrustedSapSSLSessionStartNB()==SS

**Comment by wknav** [comment]
Ebben az esetben tényleg a https://sslca2014-valid.e-szigno.hu/ oldalon elérhető tanúsítvány letöltésére lesz szükség.
Vagy alternatívaként lehetséges a következő cím használata is: https://srv.e-szigno.hu/microsecssl. Innen letölthető az api-test-onlinepenztargep.nav.gov.hu és az e-Szigno SSL CA 2014 tanúsítvány is.

**Comment by valyinagya** [comment]
Köszönöm a segítséget, sikerült!
