### ISSUE TITLE
Milyen esetekben lehet üres a cashRegisterStatusResult?

### ISSUE THREAD

**Issue by sinick2** [nav-gov-hu/Online-Cash-Register-Logfile#42]
Tisztelt fejlesztők!

Pontosan milyen esetekben lehet üres a cashRegisterStatusResult?

1) Adózónak nincs egy pénztárgépe se?
2) Adózónak van egy vagy több pénztárgépe, de egyik sem szolgáltatott még adatot? Szerintem ilyen nem lehet, de ha ilyen lehet (pl. sosem volt térerő), akkor ilyenkor mi a lastCommunicationDate, lastFileDate, minAvailableFileNumber, maxAvailableFileNumber értéke.
3) Előző 14 napban nem szolgáltatott adatot? (Erre, ha jól értem nem üres és dátuok vannak, minAvailableFileNumber, maxAvailableFileNumber pedig nulla)

Ha valamilyen esetet kihagytam volna, akkor kérem ismertessék velem!

Köszönöm: sinick2

**Comment by wknav** [comment]
A cashRegisterStatusResult üres abban az esetben, ha az előző 14 napban az adózó egyetlen pénztárgépe sem szolgáltatott adatot.

**Comment by sinick2** [comment]
Értem! Ha az adózónak két pénztárgépe van (A és B) és A szolgáltat adatot B viszont nem, akkor a resultba benne lesz a B vagy sem? Ha nem, akkor mikor van a specifikáció szerinti "Ha a rendszerből nem kérdezhető le az adott pénztárgéptől állomány, akkor az értéke 0." (25. pdf oldal) eset?

Köszönöm: sinick2

**Comment by wknav** [comment]
A result-ban ilyenkor nem lesz benne a B pénztárgép.
A dokumentáció sajnos hibás, a rendszer soha nem ad vissza 0 értéket a lekérdezhető minimális és maximális sorszámú állománynál. Javítani fogjuk a dokumentációt.

**Comment by sinick2** [comment]
Értem, köszönöm.
