### ISSUE TITLE
Milyen esetekben lehet NOT_AVAILABLE a cashRegisterFileDataResult?

### ISSUE THREAD

**Issue by sinick2** [nav-gov-hu/Online-Cash-Register-Logfile#43]
Tisztelt fejlesztők!

Pontosan milyen esetekben lehet NOT_AVAILABLE a cashRegisterFileDataResult? A dokumentációban a NOT_AVAILABLE esetre nem találtam leírást.

1. Adott pénztárgépre és/vagy naplósorszám intervallumra nincs találat?
2. Adott pénztárgép még sosem szolgáltatott még adatot? 
3. Adott pénztárgép előző 14 napban nem szolgáltatott adatot?
4. Esetleg az adott pénztárgép létezik, de pénztárgép adószám reláció hibás az Online Számla rendszerben? 
5. Esetleg csere pénztárgép eset lehet,, hogy a kihelyezett ideiglenes csere pénztárgép a szerviz adószámán van nyilvántartva?

Ha valamilyen esetet kihagytam volna, akkor kérem ismertessék velem!

Köszönöm: sinick2

**Comment by wknav** [comment]
A rendszer az elmúlt 14 napban beküldött állományokat tartalmazza.
Az állománylekérdezés mindig adott pénztárgép adott sorszámú állományaira vonatkozik (az APNumber és a fileNumberStart kötelező a kérésben). Ha nincs olyan állomány a rendszerben, ami ezeknek a feltételeknek megfelelne, akkor ad a rendszer NOT_AVAILABLE választ.

**Comment by wknav** [comment]
Kiegészítésképpen: Az adózó csak a saját pénztárgépeinek adatait láthatja. Ha a pénztárgép más adószámmal szolgáltat adatot, azt természetesen nem láthatja az adózó.

**Comment by sinick2** [comment]
Köszönöm.
