### ISSUE TITLE
[Q&A] CashRegisterFileData adatállománya

### ISSUE THREAD

**Issue by chuck0620** [nav-gov-hu/Online-Cash-Register-Logfile#44]
Tisztelt Fejlesztők!

A QueryCashRegisterFile válaszául kapott Multipart XML adatrészében a fájlok milyen tömörítéssel lettek tömörítve? A dokumentációban GZIP szerepel, de a GZIP decompress nem találja a fájl végét, így nem ismeri fel mint elfogadható tömörített fájl. 
A githubon található mintafájlban szereplő adatok kitömörítése sikerül, de az éles rendszertől kapott válaszé nem.

Előre is köszönöm a segítséget,
chuck0620

**Comment by sinick2** [comment]
Nem GZIP, hanem ZIP. 

(Írták több issue-ban is, hogy javítva lett, de nem sikerült teljesen. A specifikáció 17. oldalán javítva, a 20. és 23. oldalon még hibás, nincs nincs javítva.)

**Comment by chuck0620** [comment]
Igen, a mintaállományok kitömörítése sikerült is.

**Comment by chuck0620** [comment]
Mellékelem a fájlt amit visszakapok a kérésre. Átnéztük munkatárssal a fájlt hexában is, és nagyon sokszor ismétlődik benne az EF BF BD, ami UTF-8-as kódolásnál egy "Replacement Character". Elképzelhető, hogy rosszul kódolt fájlt kapunk? 
[Response.zip](https://github.com/nav-gov-hu/Online-Cash-Register-Logfile/files/10932842/Response.zip)

**Comment by wknav** [comment]
Első körben érdemes pl. SoapUI eszközzel megpróbálni az állományok lekérdezését.
A SoapUI a letöltött fájlokat külön attachment-ként jeleníti meg, és azokat külön le lehet menteni.

**Comment by chuck0620** [comment]
Köszönöm a tippet, azzal sikerült is feldolgozni a fájlt, illetve sikerült is megtalálni a hibát.
A kódban a HttpResponse típusú választ a ReadAsString methoddal dolgoztuk fel, mert a többi esetben ez működött, de a multipartnál ez nem működik. Helyette van egy ReadAsMultipart method, azzal beolvasva már a kódolás nem törik el, és ki lehet tömöríteni.

Köszönöm az eddigi segítséget, így meg is oldódott a probléma!
