### ISSUE TITLE
INVALID SECURITY USER

### ISSUE THREAD

**Issue by valyinagya** [nav-gov-hu/Online-Cash-Register-Logfile#45]
Üdvözlöm,

### **Az alábbi végpontra:** 
https://api-test-onlinepenztargep.nav.gov.hu/queryCashRegisterFile/v1/queryCashRegisterFile

**### Az alábbi hívással:**

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:api="http://schemas.nav.gov.hu/OPF/1.0/api" xmlns:com="http://schemas.nav.gov.hu/NTCA/1.0/common">
   <soap:Header/>
   <soap:Body>
      <api:QueryCashRegisterFileDataRequest>
         <com:header>
            <com:requestId>5176453524</com:requestId>
            <com:timestamp>2022-02-01T12:57:09Z</com:timestamp>
            <com:requestVersion>1.0</com:requestVersion>
            <com:headerVersion>1.0</com:headerVersion>
         </com:header>
         <com:user>
            <com:login>lwilsmn0wdfgz6u</com:login>
            <com:passwordHash cryptoType="SHA-512">2F43840A882CFDB7DB0FEC07D419D030D864B47B6B541DC280EF81B937B7A176E33C052B0D26638CC18A7A2C08D8D311733078A774BF43F6CA57FE8CD74DC28E</com:passwordHash>
            <com:taxNumber>12345678</com:taxNumber>
            <com:requestSignature cryptoType="SHA3-512">FDF3FB2837367E142E4B57D47A1B307D45B927E4F35DAAE73ADCED20C62E4B3C1F555B934B512BD65F64981EB7E79810A32EF9A425EE2ACF3A2640121DB96378</com:requestSignature>
			<signKey>ac-ac3a-7f661bff7d342N43CYX4U9FG</signKey>
         </com:user>
         <api:software>
            <api:softwareId>123456789123456789</api:softwareId>
            <api:softwareName>string</api:softwareName>
            <api:softwareOperation>LOCAL_SOFTWARE</api:softwareOperation>
            <api:softwareMainVersion>string</api:softwareMainVersion>
            <api:softwareDevName>string</api:softwareDevName>
            <api:softwareDevContact>string</api:softwareDevContact>
            <api:softwareDevCountryCode>HU</api:softwareDevCountryCode>
            <api:softwareDevTaxNumber>string</api:softwareDevTaxNumber>
         </api:software>
         <api:cashRegisterFileDataQuery>
            <api:APNumber>A12345678</api:APNumber>
            <api:fileNumberStart>1</api:fileNumberStart>
            <api:fileNumberEnd>2</api:fileNumberEnd>
         </api:cashRegisterFileDataQuery>
      </api:QueryCashRegisterFileDataRequest>
   </soap:Body>
</soap:Envelope>

**### Egy Invalid security user választ kapok:**

<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
   <env:Header/>
   <env:Body>
      <ns3:QueryCashRegisterFileDataResponse xmlns:ns2="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns3="http://schemas.nav.gov.hu/OPF/1.0/api">
         <ns2:header>
            <ns2:requestId>5176453524</ns2:requestId>
            <ns2:timestamp>2022-02-01T12:57:09Z</ns2:timestamp>
            <ns2:requestVersion>1.0</ns2:requestVersion>
            <ns2:headerVersion>1.0</ns2:headerVersion>
         </ns2:header>
         <ns2:result>
            <ns2:funcCode>ERROR</ns2:funcCode>
            <ns2:errorCode>INVALID_SECURITY_USER</ns2:errorCode>
            <ns2:message>Helytelen authentikációs adatok!</ns2:message>
            <ns2:notifications>
               <ns2:notification>
                  <ns2:notificationCode>NOTIFICATION_LANG</ns2:notificationCode>
                  <ns2:notificationText>HU</ns2:notificationText>
               </ns2:notification>
            </ns2:notifications>
         </ns2:result>
         <ns3:software>
            <ns3:softwareId>123456789123456789</ns3:softwareId>
            <ns3:softwareName>string</ns3:softwareName>
            <ns3:softwareOperation>LOCAL_SOFTWARE</ns3:softwareOperation>
            <ns3:softwareMainVersion>string</ns3:softwareMainVersion>
            <ns3:softwareDevName>string</ns3:softwareDevName>
            <ns3:softwareDevContact>string</ns3:softwareDevContact>
            <ns3:softwareDevCountryCode>HU</ns3:softwareDevCountryCode>
            <ns3:softwareDevTaxNumber>string</ns3:softwareDevTaxNumber>
         </ns3:software>
      </ns3:QueryCashRegisterFileDataResponse>
   </env:Body>
</env:Envelope>

Tudna kérem ebben segíteni? 

Előre is köszönöm!

**Comment by wknav** [comment]
A hiba szerint a felhasználónév és/vagy a jelszó nem megfelelő.
Mivel a hívás a teszt környezetben történt, ezért a technikai felhasználót az onlineszámla teszt környezetében kell létrehozni, ezt mindenképpen ellenőrizni kellene. (https://onlineszamla-test.nav.gov.hu/home)

**Comment by valyinagya** [comment]
A hívásban az önök által biztosított queryCashRegisterFileDataRequest.xml hívás adatait használtam, így a felhasználó gondolom egy létező felhasználó
