### ISSUE TITLE
Felcserélt gyüjtő tagek? [Q&A]

### ISSUE THREAD

**Issue by githubuser01x** [nav-gov-hu/Online-Cash-Register-Logfile#48]
Az hogyan lehetséges, hogy a leírástól eltérően vannak a tagek a letöltött fájlokban?
A leírásban így látom:
GYF | Napi forgalom forgalmi gyűjtők szerinti összesítése | lista
GYJ | Forgalmi gyűjtő jele 3 karakteren (A00..E99) | 3 karakteres szöveg
GYE | Az adott forgalmi gyűjtőbe tartozó napi tételek bruttó összértéke | 20 karakteres numerikus

Ehhez képest egy ügyfelünk fájljaiban így látom:
`<GYJ>
<GYF>C00</GYF>
<GYE>58430</GYE>
</GYJ>`

A GYF és a GYJ fel van cserélve. Nem csak egy, hanem az összes naplóban. Valamint hiányzik (szintén mindegyikből) a CNC tag is. Ez így helyes? Milyen esetben fordulhat ez így elő?

**Comment by harmatilaszlo** [comment]
Szia!  Nézd meg, hogy milyen verzióval szolgáltat adatot a pénztárgép. Itt nagy valószínűséggel még 1.0-val...

**Comment by githubuser01x** [comment]
Szia

Úgy látom, hogy ez lehet a probléma, a fájlokban ezt látom:

`semaver="v5" xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://schemas.nav.gov.hu/OPGN/1.0 AEEnaplo.xsd' xmlns='http://schemas.nav.gov.hu/OPGN/1.0'>`

míg a példa fájlokban és más ügyfeleinknél ezek már mind 2.0-ák. 

Köszönöm a segítséget!
