### ISSUE TITLE
nem várt / nem feldolgozható tartalom

### ISSUE THREAD

**Issue by NoviJayZ** [nav-gov-hu/Online-Cash-Register-Logfile#49]
Nem hiteles forássból, ezt találtam az APszámokra vonatkozóan.

AP kód összetétele:
Az AP kód első 4 karaktere a jellegzetes AP jel után a pénztárgép engedélyszáma, melyet az engedélyező hatóság határoz meg. A jelenleg forgalomban lévő pénztárgépek esetében ez minden esetben “A” betűvel kezdődik, amit egy 3 számjegyű futó sorszám követ. A következő 5 számjegy pedig a gyártó saját belső azonosítója.

Az együk partnerünk esetében kapunk adatot W00128514 AP számmal, és a 40+ összegyűjtött állományok egyikében sincs CON / COT bizonylat. NYN és NFN bizonylatok vannak benne, tehát lenne feldolgozandó adat.

Kérdés, hogy ezek az adatok miért térhetnek el a többi pg adattól, ill mit jelent az AP számban az A-től eltérő első karakter?

**Comment by renced42** [comment]
Kedves @NoviJayZ 
Ezek a pénztárgépek nem pénztárgépek, hanem élelmiszer-értékesítést kezelőszemélyzet nélkül végző automaták
Ezek az automaták az értékesítéseket ugyanúgy a Pénztárgép rendszerbe küldik, meghatározott jogszabály alapján
Mivel egy automatában nincs pénztárnyitás ezért ott nem található COT, CON bejegyzés.
Igy a W kezdet egyébként helyes

**Comment by NoviJayZ** [comment]
Köszönöm szépen!
