### ISSUE TITLE
Minta queryCashRegisterFileDataResponse.data kérése

### ISSUE THREAD

**Issue by sinick2** [nav-gov-hu/Online-Cash-Register-Logfile#5]
Tisztelt Fejlesztők!

Lehetne olyan "queryCashRegisterFileDataResponse.data" mintafájlt kérni, amiben "NFN" (vagy "NFT", azaz napi forgalmi jelentés) és "PJN" (vagy "PJT", azaz pénztárjelentés) adatok is vannak?

Könyvelőprogramokba pénztár könyveléséhez ez a két bejegyzés kell és a mintában pont ez a kettő nincs benne. A napi forgalmi jelentés áfakulcsonként, a pénztárjelentés fizetési módonként tartalmaz könyvelési adatokat.

Köszönöm

**Comment by renced42** [comment]
Kedves @sinick2 köszi a jelzést teszünk fel ilyen response adatot is. Hamarosan commitálva lesz.

**Comment by renced42** [comment]
Kedves @sinick2 tettünk fel példa állományt

**Comment by sinick2** [comment]
Kedves renced42! Köszönöm, jó leszl

(Még sztornónyugta is van, amit elfelejtettem írni a pénztárjelentés és napi forgalmi jelentés mellé!)
