### ISSUE TITLE
Hibás naplófájlok

### ISSUE THREAD

**Issue by sinick2** [nav-gov-hu/Online-Cash-Register-Logfile#51]
Tisztelt Szolgáltató!

Relative elég sok olyan naplófájl tölthető le az Online Számla rendszerből, ami hibás, feldolgozhatatlan XML-t tartalmaz, mert a fájlban hibás xml tag-ek vannak.

Például:
```
"<ZQQ>" helyett "<Zx82xCDQQ>"
"<CPY>" helyett "<x82HxC1CPY>"
"</ITL>" helyett "</ITLx82b>"
```
Az "x" után két karakteren hexadecimális szám van. Emiatt az xml feldolgozók nem tudják betölteni ezeket az állományokat. 

Kérdéseim:
1. Ezek naplóállományok hibásak minősíthetők? (A fileValidationResultCode szerint nem hibás az állomány, illetve ha van is hiba, az nem emiatt van.)
2. Lehetséges, hogy a NAV rendszere "szemetel" bele az állományokba, mikor előállítja azokat?
3. Ha nem, akkor hol lehet hivatalosan jelezni a hibás pénztárgép működést?

Köszönöm, sinick2

**Comment by renced42** [comment]
Kedves @sinick2 

A NAV rendszere azt a naplóállományt adja vissza amit a pénztárgép beküld. Tehát nem teszünk hozzá és nem is veszünk el belőle.
A példa egyértelműen hibás, hiszen az XML szintaxis eleve nem jó.
Amennyiben az opg.helpdesk@nav.gov.hu email címre megírod a problémás pénztárgép naplóállományainak nevét (hivatkozz erre az issue-ra), akkor ki tudjuk vizsgálni a hiba okát és jelezni tudunk a gyártónak/Forgalmazónak is.
Illetve megnézzük, hogy adott állományra milyen hibaüzenetet adunk.

**Comment by sinick2** [comment]
Rendben, köszönöm a választ.

**Comment by sinick2** [comment]
Tisztelt Szolgáltató!

Az állományokat megvizsgálták és azok valóban tartalmaznak hibás xml tag-eket. Nincs rá a "fileValidation" megfelelően töltve, ezért javasolnám, hogy legyen rá "XML_ERROR".

Köszönöm, sinick2

**Comment by wknav** [comment]
Kedves @sinick2!

A hiba javításra került, a hibás karaktereket tartalmazó állományok XSD_ERROR hibával megjelölésre kerülnek.
