### ISSUE TITLE
[Q&A] queryCashRegisterStatus szolgáltatás válasza hiányos csoportos lekérdezés esetén

### ISSUE THREAD

**Issue by SiposElek** [nav-gov-hu/Online-Cash-Register-Logfile#55]
Sziasztok!

Azt vettük észre, hogy éles szerveren a queryCashRegisterStatus szolgáltatás válaszában (QueryCashRegisterStatusResponse) nem található meg olyan pénztárgépnek a státusza csoportos lekérdezés esetén, amelynek külön, önmagában lekérdezve megkapjuk a státuszát.

Kiírattuk log fájba a kérés válasz kommunikációt. Előbb egy csoportos státusz lekérdezést hajtottunk végre, amire kaptunk egy szerintünk hiányos választ, mert az A12345678 számú pénztárgép státusza nem szerepel a válaszban. Utána pedig ennek a pénztárgépnek kérdezzük le a sátuszát, amelyre kapunk választ. Szeretnénk tudni, hogy ez szándékos működés, vagy esetleg hibás működés a NAV szerver részéről? Ha hibás működés, akkor mikor várható a javítás? Azt figyeltük meg, hogy ha a lekérdezésben a három megelőző pénztárgép lekérdezését kihagyjuk (jelenleg ezeknél nincs elérhető napló a szerveren), akkor megkapjuk a válaszban a A12345678 pénztárgép státuszát a csoportos lekérdezésre is. Előre is köszönöm a választ!

**Comment by wknav** [comment]
Szia!

Kérlek küldj egy olyan requestId-t, amire rossz válasz érkezett.

**Comment by SiposElek** [comment]
A request ID: R_13899996215_7404886641754
A kérésben szereplő utolsó pénztárgépre kellett volna jönnie a válasznak, de nem jött.
A fenti kommentemben az A12345678 persze csak egy fiktív példa volt.

**Comment by wknav** [comment]
Szia!

A hiba javításra került, kérlek próbáld ki.

Köszönöm!

**Comment by SiposElek** [comment]
Kipróbáltuk. Jól működik.
Köszönjük a javítást!
