### ISSUE TITLE
[Q&A] NOT_REGISTERED_CUSTOMER

### ISSUE THREAD

**Issue by e-lias** [nav-gov-hu/Online-Cash-Register-Logfile#56]
Üdv!
NOT_REGISTERED_CUSTOMER hiba mikor fordul elő? Most generáltuk a technikai felhasználót, és ez a válasz rá. A dokumentáció pdf-ében nem találtam erre utaló nyomot.
Köszönöm!

**Comment by renced42** [comment]
Kérdés, hogy hol generáltad a felhasználót és melyik rendszerben próbálkozol vele.
Az Éles és Teszt Rendszer nem átjárható.

**Comment by e-lias** [comment]
Élesben lett geenrálva, és ott is próbálom. Tudom, hogy itt a sandbox-ra vonatkoznak a kérdések, de a hibakódot nem találtam seholsem.

**Comment by renced42** [comment]
A fejlesztési specifikációban egész pontosan ez van:

a kérésben megadott adózó nincs regisztrálva A user tagban megadott adószám nem regisztrált adózóhoz tartozik.
3.2 -es fejezet Technikai Hibakódok

**Comment by e-lias** [comment]
Bocsánat, a pdf keresője viccelt meg. Köszönöm szépen!
