### ISSUE TITLE
[Q&A] Éles környezet mikor indul?

### ISSUE THREAD

**Issue by vbela75x** [nav-gov-hu/Online-Cash-Register-Logfile#6]
A kérdés, amire választ szeretnék kapni / The question I would like to be answered
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Az éles környezet várhatóan mikor indul. Rengeteg AP számom és jogosultságom van így nem szeretnék időt tölteni teszt adatok generálásává. A letöltés szeretném próbálni inkább.

**Comment by blaky** [comment]
A sajtóközleményben írták, hogy az év végén várható, de egyet értek veled, jobb lenne a letöltési funkciót élesben kiprobálni. Ez nem egy write API, felhasználói oldalról nem nagyon lehet a dolgot elrontani.

**Comment by renced42** [comment]
Kedves @vbela75x, @blaky A közlemény szerint megvárjuk a visszajelzéseket és a plusz igényeket. Ezt elemezzük és ennek megfelelően fogunk dönteni az indulásról, Ez némi idő, tehát a közlemény az irányadó :). Más részről a rendszerben ugyan van mozgás, de nem látom, hogy valaki még hibátlanul meg tudta volna hívni a szolgáltatást. Addig amíg ez így van biztosan nem indulunk el élesen.

**Comment by blaky** [comment]
@renced42, Köszi a gyors választ! 👍🏻 Akkor megpróbálom a helyesen meghívók táborát népesíteni! :-)
