### ISSUE TITLE
Teszt környete mikor fog élni?

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Cash-Register-Logfile#7]
Nem él még a teszt környezet, holott 10.11től élnie kellene,

com.sun.xml.ws.wsdl.parser.InaccessibleWSDLException: 2 counts of InaccessibleWSDLException.

java.io.IOException: Server returned HTTP response code: 405 for URL: https://api-test-onlinepenztargep.nav.gov.hu/generateCashRegisterTestData/v1/generateCashRegisterTestData
java.io.IOException: Server returned HTTP response code: 405 for URL: https://api-test-onlinepenztargep.nav.gov.hu/generateCashRegisterTestData/v1/generateCashRegisterTestData?wsdl

**Comment by renced42** [comment]
Kedves @EPluribusUnum, biztos, hogy él, mert látunk benne mozgást már néhány adózótól :) 
A hiba arra vonatkozik, hogy a GET metodus nem engedélyezett a kiszolgálón.
