### ISSUE TITLE
[Q&A] Nyugták valutában

### ISSUE THREAD

**Issue by blaky** [nav-gov-hu/Online-Cash-Register-Logfile#8]
A kérdés, amire választ szeretnék kapni / The question I would like to be answered

A generált teszt állományok között több is van, amelyik a `ZQQ` mezők alapján euróban tartalmazzák az összegeket (pl `A12345679_23553334_20200722121054_64.xml`), de nem található a`FEV` node, ami a valuta nevét és a váltáshoz szükséges információkat kéne tartalmazza a 48/2013. (XI. 15.) NGM rendeletet alapján. Továbbá ezekben a példákban a SUM mező értéke a ZQQ-ban nyomtatott euró értékkel azonos, pedig a rendeletben levő specifikáció szerint forintban kéne az összeget tartalmaznia.

A kérdésem az lenne, hogy a példák nem teljesen validak vagy csak én nem értettem meg pár pontos részletet a valutakezeléssel kapcsolatban?

Példa nyugta:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/4557844/196035751-7298a4ae-2ab4-4449-9c54-c81e3d2c4357.png">

**Comment by renced42** [comment]
Kedves @blaky A nyugta adatok a pénztárgép kükönböző működését szimulálják.
Ezek a nyugták olyan nyugták ahol a pénztárgép már EURO üzemmódban működik. Habár ilyen mostanában nem lesz ezt a funkciót is tudnia kell a PTG-nek :).
A példanyugták tartalma arra szolgál, hogy ki lehessen próbálni, hogy az letölthető XSD valid és feldolgozható a kliens számára.

**Comment by blaky** [comment]
Kedves @renced42 , Köszönöm a gyors, hétvégi választ!
