### ISSUE TITLE
internal server error 500

### ISSUE THREAD

**Issue by jsz66** [nav-gov-hu/Online-Cash-Register-Logfile#9]
Mi okozhatja, hogy a pénztárgép állapotának lekérdezésekor (queryCashRegisterStatusRequest) internal server error 500 hibaüzenetet kapok, hiányzó gyökérelem. A közzétett minta használatával is ez a válasz.

**Comment by renced42** [comment]
Kedves @jsz66 kérlek küld el a kérést ha tudod. Szinte biztos, hogy a kérés nem jó, én most leteszteltem és tökéletesen működik.

**Comment by jsz66** [comment]
[send.zip](https://github.com/nav-gov-hu/Online-Cash-Register-Logfile/files/9809422/send.zip)

**Comment by hepplaszlo** [comment]
nekünk most ez a hibaüzenet jön vissza: <ns2:funcCode>ERROR</ns2:funcCode><ns2:errorCode>OPERATION_FAILED</ns2:errorCode><ns2:message>Feldolgozás sikertelen!</ns2:message>

**Comment by pigator** [comment]
> nekünk most ez a hibaüzenet jön vissza: ns2:funcCodeERROR</ns2:funcCode>ns2:errorCodeOPERATION_FAILED</ns2:errorCode>ns2:messageFeldolgozás sikertelen!</ns2:message>

Szia!
Pedig működik rendben. Kipróbáltam, létrehoztam egy új pénztárgépet (generateCashRegisterTestData) utána lekérdeztem az első két fájlt (queryCashRegisterFile). Rendben működött a queryCashRegisterStatus is.

**Comment by renced42** [comment]
> > nekünk most ez a hibaüzenet jön vissza: ns2:funcCodeERROR</ns2:funcCode>ns2:errorCodeOPERATION_FAILED</ns2:errorCode>ns2:messageFeldolgozás sikertelen!</ns2:message>
> 
> Szia! Pedig működik rendben. Kipróbáltam, létrehoztam egy új pénztárgépet (generateCashRegisterTestData) utána lekérdeztem az első két fájlt (queryCashRegisterFile). Rendben működött a queryCashRegisterStatus is.

Kedves @pigator Az OPERATION_FAILED váratlan feldolgozási hiba esetén jön. Megnézzük a logokat, mi okozta.

**Comment by pigator** [comment]
> Kedves @pigator A passwordHash és a requestSignature mezőben a hash értékeket csupa nagybetűvel kell írni.

Köszi, de pont én írtam, hogy rendben működik nálam minden.

**Comment by hepplaszlo** [comment]
Köszönöm, működik is :) Egy élő pénztárgépet még nem lehet lekérdezni egy adózónál, akinél van meghatalmazás? Csak a generált pénztárgépeket?

**Comment by jsz66** [comment]
A #10-es issue-ban blaky javaslata megoldotta a server error 500 hibát.

**Comment by renced42** [comment]
> Köszönöm, működik is :) Egy élő pénztárgépet még nem lehet lekérdezni egy adózónál, akinél van meghatalmazás? Csak a generált pénztárgépeket?

Kedves @jsz66 Igen, így van még nem lehet lekérdezni.
